SET(OS_CONTRIB_FREETYPE_SRC
./src/base/ftapi.c
./src/base/ftbase.c
./src/base/ftbbox.c
./src/base/ftbdf.c
./src/base/ftbitmap.c
./src/base/ftcalc.c
./src/base/ftdbgmem.c
./src/base/ftdebug.c
./src/base/ftgloadr.c
./src/base/ftglyph.c
./src/base/ftinit.c
./src/base/ftmm.c
./src/base/ftnames.c
./src/base/ftobjs.c
./src/base/ftotval.c
./src/base/ftoutln.c
./src/base/ftpfr.c
./src/base/ftrfork.c
./src/base/ftstream.c
./src/base/ftstroke.c
./src/base/ftsynth.c
./src/base/ftsystem.c
./src/base/fttrigon.c
./src/base/fttype1.c
./src/base/ftutil.c
./src/base/ftwinfnt.c
./src/base/ftxf86.c
./src/bdf/bdf.c
./src/bdf/bdfdrivr.c
./src/bdf/bdflib.c
#./src/cache/ftcache.c
./src/cache/ftcbasic.c
./src/cache/ftccache.c
./src/cache/ftccmap.c
./src/cache/ftcglyph.c
./src/cache/ftcimage.c
./src/cache/ftcmanag.c
./src/cache/ftcmru.c
./src/cache/ftcsbits.c
./src/cff/cff.c
./src/cff/cffcmap.c
./src/cff/cffdrivr.c
./src/cff/cffgload.c
./src/cff/cffload.c
./src/cff/cffobjs.c
./src/cff/cffparse.c
./src/cid/cidgload.c
./src/cid/cidload.c
./src/cid/cidobjs.c
./src/cid/cidparse.c
./src/cid/cidriver.c
./src/cid/type1cid.c
./src/gzip/adler32.c
./src/gzip/ftgzip.c
./src/gzip/infblock.c
./src/gzip/infcodes.c
./src/gzip/inflate.c
./src/gzip/inftrees.c
./src/gzip/infutil.c
./src/gzip/zutil.c
./src/otvalid/otvalid.c
./src/otvalid/otvbase.c
./src/otvalid/otvcommn.c
./src/otvalid/otvgdef.c
./src/otvalid/otvgpos.c
./src/otvalid/otvgsub.c
./src/otvalid/otvjstf.c
./src/otvalid/otvmod.c
./src/pcf/pcf.c
./src/pcf/pcfdrivr.c
./src/pcf/pcfread.c
./src/pcf/pcfutil.c
./src/pfr/pfr.c
./src/pfr/pfrcmap.c
./src/pfr/pfrdrivr.c
./src/pfr/pfrgload.c
./src/pfr/pfrload.c
./src/pfr/pfrobjs.c
./src/pfr/pfrsbit.c
./src/psaux/psaux.c
./src/psaux/psauxmod.c
./src/psaux/psobjs.c
./src/psaux/t1cmap.c
./src/psaux/t1decode.c
./src/pshinter/pshalgo.c
./src/pshinter/pshglob.c
./src/pshinter/pshinter.c
./src/pshinter/pshmod.c
./src/pshinter/pshrec.c
./src/psnames/psmodule.c
./src/psnames/psnames.c
./src/raster/ftraster.c
./src/raster/ftrend1.c
./src/raster/raster.c
./src/sfnt/sfdriver.c
./src/sfnt/sfnt.c
./src/sfnt/sfobjs.c
./src/sfnt/ttcmap.c
./src/sfnt/ttkern.c
./src/sfnt/ttload.c
./src/sfnt/ttpost.c
./src/sfnt/ttsbit.c
./src/smooth/ftgrays.c
./src/smooth/ftsmooth.c
./src/smooth/smooth.c
./src/truetype/truetype.c
./src/truetype/ttdriver.c
./src/truetype/ttgload.c
./src/truetype/ttgxvar.c
./src/truetype/ttinterp.c
./src/truetype/ttobjs.c
./src/truetype/ttpload.c
./src/type1/t1afm.c
./src/type1/t1driver.c
./src/type1/t1gload.c
./src/type1/t1load.c
./src/type1/t1objs.c
./src/type1/t1parse.c
./src/type1/type1.c
./src/type42/t42drivr.c
./src/type42/t42objs.c
./src/type42/t42parse.c
./src/type42/type42.c
./src/winfonts/winfnt.c
#clang debug
./src/autofit/afglobal.c
./src/autofit/afangles.c
./src/autofit/afdummy.c
./src/autofit/afhints.c
./src/autofit/aflatin.c
./src/autofit/afloader.c
./src/autofit/afmodule.c
./src/autofit/autofit.c
#more see list.txt
)
