SET(OS_CONTRIB_DIRECTFB_SRC
./inputdrivers/dynapro/dynapro.c
./inputdrivers/elo/elo.c
./inputdrivers/gunze/gunze.c
./inputdrivers/joystick/joystick.c
./inputdrivers/keyboard/keyboard.c
#./inputdrivers/linux_input/linux_input.c
./inputdrivers/lirc/lirc.c
./inputdrivers/mutouch/mutouch.c
./inputdrivers/penmount/penmount.c
./inputdrivers/ps2mouse/ps2mouse.c
./inputdrivers/serialmouse/serialmouse.c
./inputdrivers/sonypi/sonypi.c
./inputdrivers/tslib/tslib.c
./inputdrivers/ucb1x00_ts/ucb1x00_ts.c
./inputdrivers/wm97xx_ts/wm97xx_ts.c
./interfaces/IDirectFBFont/idirectfbfont_default.c
./interfaces/IDirectFBFont/idirectfbfont_ft2.c
./interfaces/IDirectFBImageProvider/idirectfbimageprovider_dfiff.c
./interfaces/IDirectFBImageProvider/idirectfbimageprovider_gif.c
./interfaces/IDirectFBImageProvider/idirectfbimageprovider_jpeg.c
./interfaces/IDirectFBImageProvider/idirectfbimageprovider_mpeg2.c
#./interfaces/IDirectFBImageProvider/idirectfbimageprovider_png.c
./interfaces/IDirectFBImageProvider/mpeg2/getbits.c
./interfaces/IDirectFBImageProvider/mpeg2/getblk.c
./interfaces/IDirectFBImageProvider/mpeg2/gethdr.c
./interfaces/IDirectFBImageProvider/mpeg2/getpic.c
./interfaces/IDirectFBImageProvider/mpeg2/getvlc.c
./interfaces/IDirectFBImageProvider/mpeg2/idct.c
./interfaces/IDirectFBImageProvider/mpeg2/idctref.c
./interfaces/IDirectFBImageProvider/mpeg2/motion.c
./interfaces/IDirectFBImageProvider/mpeg2/mpeg2dec.c
./interfaces/IDirectFBImageProvider/mpeg2/recon.c
./interfaces/IDirectFBImageProvider/mpeg2/store.c
./interfaces/IDirectFBImageProvider/mpeg2/systems.c
./interfaces/IDirectFBVideoProvider/idirectfbvideoprovider_gif.c
./lib/direct/clock.c
./lib/direct/conf.c
./lib/direct/debug.c
./lib/direct/direct.c
./lib/direct/dtest.c
./lib/direct/hash.c
./lib/direct/interface.c
./lib/direct/list.c
#./lib/direct/log.c
./lib/direct/mem.c
./lib/direct/memcpy.c
./lib/direct/messages.c
./lib/direct/modules.c
./lib/direct/signals.c
#./lib/direct/stream.c
./lib/direct/system.c
./lib/direct/thread.c
./lib/direct/trace.c
./lib/direct/tree.c
./lib/direct/utf8.c
./lib/direct/util.c
./lib/fusion/arena.c
./lib/fusion/call.c
./lib/fusion/conf.c
./lib/fusion/fusion.c
./lib/fusion/hash.c
./lib/fusion/lock.c
./lib/fusion/object.c
./lib/fusion/property.c
./lib/fusion/reactor.c
./lib/fusion/ref.c
./lib/fusion/shmalloc.c
./lib/fusion/shm/heap.c
./lib/fusion/shm/shm.c
./lib/fusion/vector.c
#./lib/voodoo/client.c
./lib/voodoo/conf.c
./lib/voodoo/interface.c
./lib/voodoo/manager.c
./lib/voodoo/server.c
./proxy/dispatcher/idirectfbdatabuffer_dispatcher.c
./proxy/dispatcher/idirectfb_dispatcher.c
./proxy/dispatcher/idirectfbdisplaylayer_dispatcher.c
./proxy/dispatcher/idirectfbeventbuffer_dispatcher.c
./proxy/dispatcher/idirectfbfont_dispatcher.c
./proxy/dispatcher/idirectfbimageprovider_dispatcher.c
./proxy/dispatcher/idirectfbinputdevice_dispatcher.c
./proxy/dispatcher/idirectfbpalette_dispatcher.c
./proxy/dispatcher/idirectfbscreen_dispatcher.c
./proxy/dispatcher/idirectfbsurface_dispatcher.c
./proxy/dispatcher/idirectfbwindow_dispatcher.c
./proxy/requestor/idirectfbdatabuffer_requestor.c
./proxy/requestor/idirectfbdisplaylayer_requestor.c
./proxy/requestor/idirectfbeventbuffer_requestor.c
./proxy/requestor/idirectfbfont_requestor.c
./proxy/requestor/idirectfbimageprovider_requestor.c
./proxy/requestor/idirectfbinputdevice_requestor.c
./proxy/requestor/idirectfbpalette_requestor.c
./proxy/requestor/idirectfb_requestor.c
./proxy/requestor/idirectfbscreen_requestor.c
./proxy/requestor/idirectfbsurface_requestor.c
./proxy/requestor/idirectfbwindow_requestor.c
./src/core/clipboard.c
./src/core/colorhash.c
#./src/core/core.c
./src/core/core_parts.c
./src/core/fonts.c
#./src/core/gfxcard.c
#./src/core/input.c
./src/core/layer_context.c
./src/core/layer_control.c
./src/core/layer_region.c
./src/core/layers.c
./src/core/local_surface_pool.c
./src/core/palette.c
./src/core/prealloc_surface_pool.c
./src/core/screen.c
./src/core/screens.c
./src/core/shared_surface_pool.c
./src/core/state.c
./src/core/surface_buffer.c
./src/core/surface.c
./src/core/surface_core.c
./src/core/surface_pool.c
#./src/core/system.c
./src/core/windows.c
#./src/core/windowstack.c
#./src/core/wm.c
#./src/directfb.c
./src/display/idirectfbdisplaylayer.c
./src/display/idirectfbpalette.c
./src/display/idirectfbscreen.c
./src/display/idirectfbsurface.c
./src/display/idirectfbsurface_layer.c
./src/display/idirectfbsurface_window.c
./src/gfx/clip.c
./src/gfx/convert.c
./src/gfx/util.c
./src/idirectfb.c
./src/input/idirectfbinputbuffer.c
./src/input/idirectfbinputdevice.c
./src/media/idirectfbdatabuffer.c
./src/media/idirectfbdatabuffer_file.c
./src/media/idirectfbdatabuffer_memory.c
./src/media/idirectfbdatabuffer_streamed.c
./src/media/idirectfbfont.c
./src/media/idirectfbimageprovider.c
./src/media/idirectfbvideoprovider.c
#./src/misc/conf.c
./src/misc/gfx_util.c
./src/misc/util.c
./src/windows/idirectfbwindow.c
#./systems/x11/primary.c
#./systems/x11/x11.c
#./systems/x11/x11image.c
#./systems/x11/x11input.c
#./systems/x11/x11_surface_pool.c
#./systems/x11/xwindow.c
#both

./gfxdrivers/cle266/uc_accel.c
./gfxdrivers/cle266/uc_fifo.c
./gfxdrivers/cle266/uc_hwmap.c
./gfxdrivers/cle266/uc_hwset.c
./gfxdrivers/cle266/uc_overlay.c
./gfxdrivers/cle266/uc_ovl_hwmap.c
./gfxdrivers/cle266/uc_ovl_hwset.c
./gfxdrivers/cle266/uc_primary.c
./gfxdrivers/cle266/uc_state.c
./gfxdrivers/cle266/unichrome.c
#./gfxdrivers/unichrome/uc_accel.c
#./gfxdrivers/unichrome/uc_fifo.c
#./gfxdrivers/unichrome/uc_hwmap.c
#./gfxdrivers/unichrome/uc_hwset.c
#./gfxdrivers/unichrome/uc_overlay.c
#./gfxdrivers/unichrome/uc_ovl_hwmap.c
#./gfxdrivers/unichrome/uc_ovl_hwset.c
#./gfxdrivers/unichrome/uc_primary.c
#./gfxdrivers/unichrome/uc_spic.c
#./gfxdrivers/unichrome/uc_state.c
#./gfxdrivers/unichrome/unichrome.c
./lib/fusion/shm/pool.c
#./lib/fusion/shm/fake.c
#demo
./src/gfx/generic/generic.c
#./src/gfx/generic/yuvtbl-gen.c
#clang debug
./gfxdrivers/ati128/ati128.c
./gfxdrivers/ati128/ati128_overlay.c
./gfxdrivers/ati128/ati128_state.c
./gfxdrivers/cyber5k/cyber5k_alpha.c
./gfxdrivers/cyber5k/cyber5k.c
./gfxdrivers/cyber5k/cyber5k_overlay.c
./gfxdrivers/cyber5k/cyber5k_underlay.c
./gfxdrivers/davinci/davinci_2d.c
./gfxdrivers/davinci/davinci_c64x.c
./gfxdrivers/davinci/davinci_gfxdriver.c
./gfxdrivers/davinci/davinci_osd.c
./gfxdrivers/davinci/davinci_osd_pool.c
./gfxdrivers/davinci/davinci_screen.c
./gfxdrivers/davinci/davinci_video.c
./gfxdrivers/davinci/davinci_video_pool.c
./gfxdrivers/i810/i810.c
./gfxdrivers/i810/i810_overlay.c
./gfxdrivers/i830/i830.c
./gfxdrivers/i830/i830_overlay.c
./gfxdrivers/mach64/mach64.c
./gfxdrivers/mach64/mach64_overlay.c
./gfxdrivers/mach64/mach64_state.c
./gfxdrivers/matrox/matrox_3d.c
./gfxdrivers/matrox/matrox_bes.c
./gfxdrivers/matrox/matrox.c
./gfxdrivers/matrox/matrox_crtc2.c
./gfxdrivers/matrox/matrox_maven.c
./gfxdrivers/matrox/matrox_screen_crtc2.c
./gfxdrivers/matrox/matrox_spic.c
./gfxdrivers/matrox/matrox_state.c
./gfxdrivers/neomagic/neo2200.c
./gfxdrivers/neomagic/neomagic.c
./gfxdrivers/neomagic/neo_overlay.c
./gfxdrivers/nsc/nsc.c
./gfxdrivers/nsc/nsc_galfns.c
./gfxdrivers/nvidia/nvidia_2d.c
./gfxdrivers/nvidia/nvidia_3d.c
./gfxdrivers/nvidia/nvidia.c
./gfxdrivers/nvidia/nvidia_overlay.c
./gfxdrivers/nvidia/nvidia_primary.c
./gfxdrivers/nvidia/nvidia_state.c
#./gfxdrivers/omap/omap.c
#./gfxdrivers/omap/omap_primary.c
./gfxdrivers/radeon/r100_3d.c
./gfxdrivers/radeon/r100_state.c
./gfxdrivers/radeon/r200_3d.c
./gfxdrivers/radeon/r200_state.c
./gfxdrivers/radeon/r300_3d.c
./gfxdrivers/radeon/r300_state.c
./gfxdrivers/radeon/radeon_2d.c
./gfxdrivers/radeon/radeon.c
./gfxdrivers/radeon/radeon_crtc1.c
./gfxdrivers/radeon/radeon_crtc2.c
./gfxdrivers/radeon/radeon_overlay.c
./gfxdrivers/savage/savage2000.c
./gfxdrivers/savage/savage3d.c
./gfxdrivers/savage/savage4.c
./gfxdrivers/savage/savage.c
./gfxdrivers/sis315/sis315_accel.c
./gfxdrivers/sis315/sis315.c
./gfxdrivers/sis315/sis315_mmio.c
./gfxdrivers/sis315/sis315_state.c
./gfxdrivers/tdfx/tdfx.c
./gfxdrivers/vmware/vmware_2d.c
./gfxdrivers/vmware/vmware_gfxdriver.c
#./gfxdrivers/davinci/kernel-module/c64x/c64x.c
#more see list.txt
)
