SET(OS_CONTRIB_LIBMNG_SRC
./libmng_error.c
./libmng_pixels.c
./libmng_jpeg.c
./libmng_chunk_io.c
./libmng_prop_xs.c
./libmng_dither.c
./libmng_write.c
./libmng_chunk_xs.c
./libmng_display.c
./libmng_callback_xs.c
./libmng_object_prc.c
./libmng_chunk_descr.c
./libmng_trace.c
./libmng_chunk_prc.c
./libmng_filter.c
./libmng_cms.c
./libmng_zlib.c
./libmng_read.c
./libmng_hlapi.c
)
