# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/samuel/build/1.08

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/samuel/build/1.08

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/samuel/build/1.08/CMakeFiles /home/samuel/build/1.08/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/samuel/build/1.08/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lib

# Build rule for target.
lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib
.PHONY : lib

# fast build rule for target.
lib/fast:
	$(MAKE) -f lib/CMakeFiles/lib.dir/build.make lib/CMakeFiles/lib.dir/build
.PHONY : lib/fast

#=============================================================================
# Target rules for targets named lib_staic

# Build rule for target.
lib_staic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_staic
.PHONY : lib_staic

# fast build rule for target.
lib_staic/fast:
	$(MAKE) -f lib/CMakeFiles/lib_staic.dir/build.make lib/CMakeFiles/lib_staic.dir/build
.PHONY : lib_staic/fast

#=============================================================================
# Target rules for targets named net

# Build rule for target.
net: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net
.PHONY : net

# fast build rule for target.
net/fast:
	$(MAKE) -f net/CMakeFiles/net.dir/build.make net/CMakeFiles/net.dir/build
.PHONY : net/fast

#=============================================================================
# Target rules for targets named net_staic

# Build rule for target.
net_staic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_staic
.PHONY : net_staic

# fast build rule for target.
net_staic/fast:
	$(MAKE) -f net/CMakeFiles/net_staic.dir/build.make net/CMakeFiles/net_staic.dir/build
.PHONY : net_staic/fast

#=============================================================================
# Target rules for targets named fs

# Build rule for target.
fs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fs
.PHONY : fs

# fast build rule for target.
fs/fast:
	$(MAKE) -f fs/CMakeFiles/fs.dir/build.make fs/CMakeFiles/fs.dir/build
.PHONY : fs/fast

#=============================================================================
# Target rules for targets named fs_staic

# Build rule for target.
fs_staic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fs_staic
.PHONY : fs_staic

# fast build rule for target.
fs_staic/fast:
	$(MAKE) -f fs/CMakeFiles/fs_staic.dir/build.make fs/CMakeFiles/fs_staic.dir/build
.PHONY : fs_staic/fast

#=============================================================================
# Target rules for targets named atom

# Build rule for target.
atom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atom
.PHONY : atom

# fast build rule for target.
atom/fast:
	$(MAKE) -f atom/CMakeFiles/atom.dir/build.make atom/CMakeFiles/atom.dir/build
.PHONY : atom/fast

#=============================================================================
# Target rules for targets named atom_staic

# Build rule for target.
atom_staic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atom_staic
.PHONY : atom_staic

# fast build rule for target.
atom_staic/fast:
	$(MAKE) -f atom/CMakeFiles/atom_staic.dir/build.make atom/CMakeFiles/atom_staic.dir/build
.PHONY : atom_staic/fast

#=============================================================================
# Target rules for targets named bsp

# Build rule for target.
bsp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bsp
.PHONY : bsp

# fast build rule for target.
bsp/fast:
	$(MAKE) -f bsp/CMakeFiles/bsp.dir/build.make bsp/CMakeFiles/bsp.dir/build
.PHONY : bsp/fast

#=============================================================================
# Target rules for targets named bsp_staic

# Build rule for target.
bsp_staic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bsp_staic
.PHONY : bsp_staic

# fast build rule for target.
bsp_staic/fast:
	$(MAKE) -f bsp/CMakeFiles/bsp_staic.dir/build.make bsp/CMakeFiles/bsp_staic.dir/build
.PHONY : bsp_staic/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f contrib/zlib/CMakeFiles/zlib.dir/build.make contrib/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named zlib_static

# Build rule for target.
zlib_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib_static
.PHONY : zlib_static

# fast build rule for target.
zlib_static/fast:
	$(MAKE) -f contrib/zlib/CMakeFiles/zlib_static.dir/build.make contrib/zlib/CMakeFiles/zlib_static.dir/build
.PHONY : zlib_static/fast

#=============================================================================
# Target rules for targets named v8

# Build rule for target.
v8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 v8
.PHONY : v8

# fast build rule for target.
v8/fast:
	$(MAKE) -f contrib/v8/CMakeFiles/v8.dir/build.make contrib/v8/CMakeFiles/v8.dir/build
.PHONY : v8/fast

#=============================================================================
# Target rules for targets named bzip

# Build rule for target.
bzip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bzip
.PHONY : bzip

# fast build rule for target.
bzip/fast:
	$(MAKE) -f contrib/bzip/CMakeFiles/bzip.dir/build.make contrib/bzip/CMakeFiles/bzip.dir/build
.PHONY : bzip/fast

#=============================================================================
# Target rules for targets named bzip_static

# Build rule for target.
bzip_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bzip_static
.PHONY : bzip_static

# fast build rule for target.
bzip_static/fast:
	$(MAKE) -f contrib/bzip/CMakeFiles/bzip_static.dir/build.make contrib/bzip/CMakeFiles/bzip_static.dir/build
.PHONY : bzip_static/fast

#=============================================================================
# Target rules for targets named gzip

# Build rule for target.
gzip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gzip
.PHONY : gzip

# fast build rule for target.
gzip/fast:
	$(MAKE) -f contrib/gzip/CMakeFiles/gzip.dir/build.make contrib/gzip/CMakeFiles/gzip.dir/build
.PHONY : gzip/fast

#=============================================================================
# Target rules for targets named gzip_static

# Build rule for target.
gzip_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gzip_static
.PHONY : gzip_static

# fast build rule for target.
gzip_static/fast:
	$(MAKE) -f contrib/gzip/CMakeFiles/gzip_static.dir/build.make contrib/gzip/CMakeFiles/gzip_static.dir/build
.PHONY : gzip_static/fast

#=============================================================================
# Target rules for targets named expat

# Build rule for target.
expat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expat
.PHONY : expat

# fast build rule for target.
expat/fast:
	$(MAKE) -f contrib/expat/CMakeFiles/expat.dir/build.make contrib/expat/CMakeFiles/expat.dir/build
.PHONY : expat/fast

#=============================================================================
# Target rules for targets named expat_static

# Build rule for target.
expat_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expat_static
.PHONY : expat_static

# fast build rule for target.
expat_static/fast:
	$(MAKE) -f contrib/expat/CMakeFiles/expat_static.dir/build.make contrib/expat/CMakeFiles/expat_static.dir/build
.PHONY : expat_static/fast

#=============================================================================
# Target rules for targets named jpeg

# Build rule for target.
jpeg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jpeg
.PHONY : jpeg

# fast build rule for target.
jpeg/fast:
	$(MAKE) -f contrib/jpeg/CMakeFiles/jpeg.dir/build.make contrib/jpeg/CMakeFiles/jpeg.dir/build
.PHONY : jpeg/fast

#=============================================================================
# Target rules for targets named jpeg_static

# Build rule for target.
jpeg_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jpeg_static
.PHONY : jpeg_static

# fast build rule for target.
jpeg_static/fast:
	$(MAKE) -f contrib/jpeg/CMakeFiles/jpeg_static.dir/build.make contrib/jpeg/CMakeFiles/jpeg_static.dir/build
.PHONY : jpeg_static/fast

#=============================================================================
# Target rules for targets named libmng

# Build rule for target.
libmng: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libmng
.PHONY : libmng

# fast build rule for target.
libmng/fast:
	$(MAKE) -f contrib/libmng/CMakeFiles/libmng.dir/build.make contrib/libmng/CMakeFiles/libmng.dir/build
.PHONY : libmng/fast

#=============================================================================
# Target rules for targets named libmng_static

# Build rule for target.
libmng_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libmng_static
.PHONY : libmng_static

# fast build rule for target.
libmng_static/fast:
	$(MAKE) -f contrib/libmng/CMakeFiles/libmng_static.dir/build.make contrib/libmng/CMakeFiles/libmng_static.dir/build
.PHONY : libmng_static/fast

#=============================================================================
# Target rules for targets named libogg

# Build rule for target.
libogg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libogg
.PHONY : libogg

# fast build rule for target.
libogg/fast:
	$(MAKE) -f contrib/libogg/CMakeFiles/libogg.dir/build.make contrib/libogg/CMakeFiles/libogg.dir/build
.PHONY : libogg/fast

#=============================================================================
# Target rules for targets named libogg_static

# Build rule for target.
libogg_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libogg_static
.PHONY : libogg_static

# fast build rule for target.
libogg_static/fast:
	$(MAKE) -f contrib/libogg/CMakeFiles/libogg_static.dir/build.make contrib/libogg/CMakeFiles/libogg_static.dir/build
.PHONY : libogg_static/fast

#=============================================================================
# Target rules for targets named libpng

# Build rule for target.
libpng: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libpng
.PHONY : libpng

# fast build rule for target.
libpng/fast:
	$(MAKE) -f contrib/libpng/CMakeFiles/libpng.dir/build.make contrib/libpng/CMakeFiles/libpng.dir/build
.PHONY : libpng/fast

#=============================================================================
# Target rules for targets named libpng_static

# Build rule for target.
libpng_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libpng_static
.PHONY : libpng_static

# fast build rule for target.
libpng_static/fast:
	$(MAKE) -f contrib/libpng/CMakeFiles/libpng_static.dir/build.make contrib/libpng/CMakeFiles/libpng_static.dir/build
.PHONY : libpng_static/fast

#=============================================================================
# Target rules for targets named libxml

# Build rule for target.
libxml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libxml
.PHONY : libxml

# fast build rule for target.
libxml/fast:
	$(MAKE) -f contrib/libxml/CMakeFiles/libxml.dir/build.make contrib/libxml/CMakeFiles/libxml.dir/build
.PHONY : libxml/fast

#=============================================================================
# Target rules for targets named libxml_static

# Build rule for target.
libxml_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libxml_static
.PHONY : libxml_static

# fast build rule for target.
libxml_static/fast:
	$(MAKE) -f contrib/libxml/CMakeFiles/libxml_static.dir/build.make contrib/libxml/CMakeFiles/libxml_static.dir/build
.PHONY : libxml_static/fast

#=============================================================================
# Target rules for targets named pixman

# Build rule for target.
pixman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pixman
.PHONY : pixman

# fast build rule for target.
pixman/fast:
	$(MAKE) -f contrib/pixman/CMakeFiles/pixman.dir/build.make contrib/pixman/CMakeFiles/pixman.dir/build
.PHONY : pixman/fast

#=============================================================================
# Target rules for targets named pixman_static

# Build rule for target.
pixman_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pixman_static
.PHONY : pixman_static

# fast build rule for target.
pixman_static/fast:
	$(MAKE) -f contrib/pixman/CMakeFiles/pixman_static.dir/build.make contrib/pixman/CMakeFiles/pixman_static.dir/build
.PHONY : pixman_static/fast

#=============================================================================
# Target rules for targets named tiff

# Build rule for target.
tiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff
.PHONY : tiff

# fast build rule for target.
tiff/fast:
	$(MAKE) -f contrib/tiff/CMakeFiles/tiff.dir/build.make contrib/tiff/CMakeFiles/tiff.dir/build
.PHONY : tiff/fast

#=============================================================================
# Target rules for targets named tiff_static

# Build rule for target.
tiff_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff_static
.PHONY : tiff_static

# fast build rule for target.
tiff_static/fast:
	$(MAKE) -f contrib/tiff/CMakeFiles/tiff_static.dir/build.make contrib/tiff/CMakeFiles/tiff_static.dir/build
.PHONY : tiff_static/fast

#=============================================================================
# Target rules for targets named tslib

# Build rule for target.
tslib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tslib
.PHONY : tslib

# fast build rule for target.
tslib/fast:
	$(MAKE) -f contrib/tslib/CMakeFiles/tslib.dir/build.make contrib/tslib/CMakeFiles/tslib.dir/build
.PHONY : tslib/fast

#=============================================================================
# Target rules for targets named tslib_static

# Build rule for target.
tslib_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tslib_static
.PHONY : tslib_static

# fast build rule for target.
tslib_static/fast:
	$(MAKE) -f contrib/tslib/CMakeFiles/tslib_static.dir/build.make contrib/tslib/CMakeFiles/tslib_static.dir/build
.PHONY : tslib_static/fast

#=============================================================================
# Target rules for targets named thttpd

# Build rule for target.
thttpd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thttpd
.PHONY : thttpd

# fast build rule for target.
thttpd/fast:
	$(MAKE) -f contrib/thttpd/CMakeFiles/thttpd.dir/build.make contrib/thttpd/CMakeFiles/thttpd.dir/build
.PHONY : thttpd/fast

#=============================================================================
# Target rules for targets named thttpd_static

# Build rule for target.
thttpd_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thttpd_static
.PHONY : thttpd_static

# fast build rule for target.
thttpd_static/fast:
	$(MAKE) -f contrib/thttpd/CMakeFiles/thttpd_static.dir/build.make contrib/thttpd/CMakeFiles/thttpd_static.dir/build
.PHONY : thttpd_static/fast

#=============================================================================
# Target rules for targets named sqlite

# Build rule for target.
sqlite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sqlite
.PHONY : sqlite

# fast build rule for target.
sqlite/fast:
	$(MAKE) -f contrib/sqlite/CMakeFiles/sqlite.dir/build.make contrib/sqlite/CMakeFiles/sqlite.dir/build
.PHONY : sqlite/fast

#=============================================================================
# Target rules for targets named sqlite_static

# Build rule for target.
sqlite_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sqlite_static
.PHONY : sqlite_static

# fast build rule for target.
sqlite_static/fast:
	$(MAKE) -f contrib/sqlite/CMakeFiles/sqlite_static.dir/build.make contrib/sqlite/CMakeFiles/sqlite_static.dir/build
.PHONY : sqlite_static/fast

#=============================================================================
# Target rules for targets named php

# Build rule for target.
php: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 php
.PHONY : php

# fast build rule for target.
php/fast:
	$(MAKE) -f contrib/php/CMakeFiles/php.dir/build.make contrib/php/CMakeFiles/php.dir/build
.PHONY : php/fast

#=============================================================================
# Target rules for targets named php_static

# Build rule for target.
php_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 php_static
.PHONY : php_static

# fast build rule for target.
php_static/fast:
	$(MAKE) -f contrib/php/CMakeFiles/php_static.dir/build.make contrib/php/CMakeFiles/php_static.dir/build
.PHONY : php_static/fast

#=============================================================================
# Target rules for targets named libvpx

# Build rule for target.
libvpx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libvpx
.PHONY : libvpx

# fast build rule for target.
libvpx/fast:
	$(MAKE) -f contrib/libvpx/CMakeFiles/libvpx.dir/build.make contrib/libvpx/CMakeFiles/libvpx.dir/build
.PHONY : libvpx/fast

#=============================================================================
# Target rules for targets named libvpx_static

# Build rule for target.
libvpx_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libvpx_static
.PHONY : libvpx_static

# fast build rule for target.
libvpx_static/fast:
	$(MAKE) -f contrib/libvpx/CMakeFiles/libvpx_static.dir/build.make contrib/libvpx/CMakeFiles/libvpx_static.dir/build
.PHONY : libvpx_static/fast

#=============================================================================
# Target rules for targets named iconv

# Build rule for target.
iconv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iconv
.PHONY : iconv

# fast build rule for target.
iconv/fast:
	$(MAKE) -f contrib/libiconv/CMakeFiles/iconv.dir/build.make contrib/libiconv/CMakeFiles/iconv.dir/build
.PHONY : iconv/fast

#=============================================================================
# Target rules for targets named iconv_static

# Build rule for target.
iconv_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iconv_static
.PHONY : iconv_static

# fast build rule for target.
iconv_static/fast:
	$(MAKE) -f contrib/libiconv/CMakeFiles/iconv_static.dir/build.make contrib/libiconv/CMakeFiles/iconv_static.dir/build
.PHONY : iconv_static/fast

#=============================================================================
# Target rules for targets named cairo

# Build rule for target.
cairo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cairo
.PHONY : cairo

# fast build rule for target.
cairo/fast:
	$(MAKE) -f contrib/cairo/CMakeFiles/cairo.dir/build.make contrib/cairo/CMakeFiles/cairo.dir/build
.PHONY : cairo/fast

#=============================================================================
# Target rules for targets named cairo_static

# Build rule for target.
cairo_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cairo_static
.PHONY : cairo_static

# fast build rule for target.
cairo_static/fast:
	$(MAKE) -f contrib/cairo/CMakeFiles/cairo_static.dir/build.make contrib/cairo/CMakeFiles/cairo_static.dir/build
.PHONY : cairo_static/fast

#=============================================================================
# Target rules for targets named freetype

# Build rule for target.
freetype: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freetype
.PHONY : freetype

# fast build rule for target.
freetype/fast:
	$(MAKE) -f contrib/freetype/CMakeFiles/freetype.dir/build.make contrib/freetype/CMakeFiles/freetype.dir/build
.PHONY : freetype/fast

#=============================================================================
# Target rules for targets named freetype_static

# Build rule for target.
freetype_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freetype_static
.PHONY : freetype_static

# fast build rule for target.
freetype_static/fast:
	$(MAKE) -f contrib/freetype/CMakeFiles/freetype_static.dir/build.make contrib/freetype/CMakeFiles/freetype_static.dir/build
.PHONY : freetype_static/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lib"
	@echo "... lib_staic"
	@echo "... net"
	@echo "... net_staic"
	@echo "... fs"
	@echo "... fs_staic"
	@echo "... atom"
	@echo "... atom_staic"
	@echo "... bsp"
	@echo "... bsp_staic"
	@echo "... zlib"
	@echo "... zlib_static"
	@echo "... v8"
	@echo "... bzip"
	@echo "... bzip_static"
	@echo "... gzip"
	@echo "... gzip_static"
	@echo "... expat"
	@echo "... expat_static"
	@echo "... jpeg"
	@echo "... jpeg_static"
	@echo "... libmng"
	@echo "... libmng_static"
	@echo "... libogg"
	@echo "... libogg_static"
	@echo "... libpng"
	@echo "... libpng_static"
	@echo "... libxml"
	@echo "... libxml_static"
	@echo "... pixman"
	@echo "... pixman_static"
	@echo "... tiff"
	@echo "... tiff_static"
	@echo "... tslib"
	@echo "... tslib_static"
	@echo "... thttpd"
	@echo "... thttpd_static"
	@echo "... sqlite"
	@echo "... sqlite_static"
	@echo "... php"
	@echo "... php_static"
	@echo "... libvpx"
	@echo "... libvpx_static"
	@echo "... iconv"
	@echo "... iconv_static"
	@echo "... cairo"
	@echo "... cairo_static"
	@echo "... freetype"
	@echo "... freetype_static"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

