SET(OS_CONTRIB_LIBRSVG_SRC
./${CURPATH}librsvg-enum-types.c
./${CURPATH}librsvg-features.c
./${CURPATH}rsvg-filter.c
./${CURPATH}rsvg-io.c
./${CURPATH}rsvg-convert.c
./${CURPATH}rsvg-cairo-clip.c
./${CURPATH}rsvg-base.c
./${CURPATH}rsvg-file-util.c
./${CURPATH}rsvg-defs.c
./${CURPATH}rsvg-structure.c
./${CURPATH}rsvg-cairo-render.c
./${CURPATH}rsvg-gobject.c
./${CURPATH}rsvg-marker.c
./${CURPATH}rsvg-cairo-draw.c
./${CURPATH}rsvg-cond.c
./${CURPATH}rsvg-paint-server.c
./${CURPATH}rsvg-size-callback.c
./${CURPATH}rsvg-base-file-util.c
./${CURPATH}rsvg-mask.c
./${CURPATH}rsvg-path.c
./${CURPATH}rsvg-css.c
./${CURPATH}rsvg-styles.c
./${CURPATH}rsvg-text.c
./${CURPATH}rsvg.c
./${CURPATH}rsvg-image.c
./${CURPATH}rsvg-shapes.c
./${CURPATH}rsvg-xml.c
#more see list.txt
)
