SET(OS_CONTRIB_JPEG_SRC
./${CURPATH}jidctfst.c
./${CURPATH}jmemmgr.c
./${CURPATH}jidctflt.c
./${CURPATH}jfdctfst.c
./${CURPATH}jdapistd.c
./${CURPATH}jcphuff.c
./${CURPATH}jerror.c
./${CURPATH}cdjpeg.c
./${CURPATH}jquant1.c
./${CURPATH}jdmainct.c
./${CURPATH}wrgif.c
./${CURPATH}wrtarga.c
./${CURPATH}jcparam.c
./${CURPATH}jcsample.c
./${CURPATH}jcapistd.c
./${CURPATH}rdppm.c
./${CURPATH}jidctint.c
./${CURPATH}jdmaster.c
./${CURPATH}jccolor.c
./${CURPATH}jutils.c
./${CURPATH}rdgif.c
./${CURPATH}jctrans.c
./${CURPATH}wrrle.c
./${CURPATH}rdrle.c
./${CURPATH}rdtarga.c
./${CURPATH}jdinput.c
./${CURPATH}jdtrans.c
./${CURPATH}jdhuff.c
./${CURPATH}jidctred.c
./${CURPATH}jdatadst.c
./${CURPATH}jdpostct.c
./${CURPATH}jdmerge.c
./${CURPATH}rdcolmap.c
./${CURPATH}jcprepct.c
./${CURPATH}rdbmp.c
./${CURPATH}jcdctmgr.c
./${CURPATH}jdapimin.c
./${CURPATH}jdphuff.c
./${CURPATH}jcapimin.c
./${CURPATH}jdatasrc.c
./${CURPATH}jfdctint.c
./${CURPATH}jdcoefct.c
./${CURPATH}jccoefct.c
./${CURPATH}jddctmgr.c
./${CURPATH}transupp.c
./${CURPATH}jcmarker.c
./${CURPATH}wrbmp.c
./${CURPATH}jcmaster.c
./${CURPATH}jcinit.c
./${CURPATH}jcmainct.c
./${CURPATH}jquant2.c
./${CURPATH}jchuff.c
./${CURPATH}wrppm.c
./${CURPATH}jfdctflt.c
./${CURPATH}jdmarker.c
./${CURPATH}jcomapi.c
./${CURPATH}jdcolor.c
./${CURPATH}jdsample.c
./${CURPATH}rdswitch.c
#both
#./${CURPATH}jmemname.c
#./${CURPATH}jmemnobs.c
./${CURPATH}jmemansi.c

#demo
#./${CURPATH}ansi2knr.c
#./${CURPATH}jmemdos.c
#./${CURPATH}jmemmac.c
#./${CURPATH}wrjpgcom.c
#./${CURPATH}rdjpgcom.c
#./${CURPATH}ckconfig.c
#./${CURPATH}cjpeg.c
#./${CURPATH}djpeg.c
#./${CURPATH}example.c
#./${CURPATH}jpegtran.c
)
