SET(OS_CONTRIB_LIBXT_SRC
./${CURPATH}src/Resources.c
./${CURPATH}src/Selection.c
./${CURPATH}src/SetWMCW.c
./${CURPATH}src/TMparse.c
./${CURPATH}src/SetValues.c
./${CURPATH}src/Manage.c
./${CURPATH}src/sharedlib.c
./${CURPATH}src/Convert.c
./${CURPATH}src/Initialize.c
./${CURPATH}src/Threads.c
./${CURPATH}src/TMprint.c
./${CURPATH}src/Vendor.c
./${CURPATH}src/TMkey.c
./${CURPATH}src/TMaction.c
./${CURPATH}src/TMstate.c
./${CURPATH}src/Hooks.c
./${CURPATH}src/SetSens.c
./${CURPATH}src/Core.c
./${CURPATH}src/Popup.c
./${CURPATH}src/Callback.c
./${CURPATH}src/PassivGrab.c
./${CURPATH}src/RectObj.c
./${CURPATH}src/ActionHook.c
./${CURPATH}src/ClickTime.c
./${CURPATH}src/VarGet.c
./${CURPATH}src/Event.c
./${CURPATH}src/PopupCB.c
./${CURPATH}src/GetResList.c
./${CURPATH}src/Keyboard.c
./${CURPATH}src/Pointer.c
./${CURPATH}src/Converters.c
./${CURPATH}src/TMgrab.c
./${CURPATH}src/VarCreate.c
./${CURPATH}src/Alloc.c
./${CURPATH}src/Display.c
./${CURPATH}src/HookObj.c
./${CURPATH}src/Geometry.c
./${CURPATH}src/GCManager.c
./${CURPATH}src/NextEvent.c
./${CURPATH}src/Create.c
./${CURPATH}src/GetValues.c
./${CURPATH}src/EventUtil.c
./${CURPATH}src/Composite.c
./${CURPATH}src/Shell.c
./${CURPATH}src/GetActKey.c
./${CURPATH}src/Functions.c
./${CURPATH}src/Varargs.c
./${CURPATH}src/Intrinsic.c
./${CURPATH}src/ResConfig.c
./${CURPATH}src/Constraint.c
./${CURPATH}src/ArgList.c
./${CURPATH}src/Object.c
./${CURPATH}src/Destroy.c
./${CURPATH}src/Error.c
./${CURPATH}util/makestrs.c
)
