SET(OS_CONTRIB_SQLITE_SRC
./src/printf.c
./src/mutex.c
./src/tclsqlite.c
./src/memjournal.c
./src/vdbesort.c
./src/mutex_w32.c
./src/table.c
./src/func.c
./src/bitvec.c
./src/utf.c
./src/backup.c
./src/pager.c
./src/date.c
./src/btree.c
./src/journal.c
./src/rowset.c
./src/complete.c
./src/legacy.c
./src/vacuum.c
./src/malloc.c
./src/pcache1.c
./src/vdbetrace.c
./src/vdbeapi.c
./src/random.c
./src/fault.c
./src/auth.c
./src/notify.c
./src/mutex_noop.c
./src/prepare.c
./src/pcache.c
./src/btmutex.c
./src/lempar.c
./src/analyze.c
./src/insert.c
./src/walker.c
./src/loadext.c
./src/vtab.c
./src/vdbemem.c
./src/util.c
./src/status.c
./src/hash.c
./src/delete.c
./src/wal.c
./src/build.c
./src/shell.c
./src/main.c
#./src/select.c
#./src/update.c
#./src/resolve.c
#./src/ctime.c
#./src/expr.c
#./src/vdbeaux.c
#./src/mutex_unix.c
#./src/vdbeblob.c
#./src/global.c
#./src/where.c
#./src/alter.c
#./src/trigger.c
#./src/vdbe.c
#./src/attach.c
#./src/tokenize.c
#./src/pragma.c
#./src/fkey.c
#demo
#./src/os.c
#./src/os_win.c
#./src/os_unix.c

#./src/callback.c
)
