SET(OS_CONTRIB_XZ_SRC
./${CURPATH}src/common/tuklib_open_stdxxx.c
./${CURPATH}src/common/tuklib_physmem.c
./${CURPATH}src/common/tuklib_progname.c
./${CURPATH}src/common/tuklib_mbstr_width.c
./${CURPATH}src/common/tuklib_mbstr_fw.c
./${CURPATH}src/common/tuklib_exit.c
./${CURPATH}src/common/tuklib_cpucores.c
./${CURPATH}src/lzmainfo/lzmainfo.c
./${CURPATH}src/liblzma/delta/delta_common.c
./${CURPATH}src/liblzma/delta/delta_decoder.c
./${CURPATH}src/liblzma/delta/delta_encoder.c
./${CURPATH}src/liblzma/common/filter_buffer_decoder.c
./${CURPATH}src/liblzma/common/index_encoder.c
./${CURPATH}src/liblzma/common/stream_encoder.c
./${CURPATH}src/liblzma/common/alone_decoder.c
./${CURPATH}src/liblzma/common/filter_encoder.c
./${CURPATH}src/liblzma/common/stream_flags_encoder.c
./${CURPATH}src/liblzma/common/block_buffer_encoder.c
./${CURPATH}src/liblzma/common/hardware_physmem.c
./${CURPATH}src/liblzma/common/auto_decoder.c
./${CURPATH}src/liblzma/common/alone_encoder.c
./${CURPATH}src/liblzma/common/vli_size.c
./${CURPATH}src/liblzma/common/block_header_encoder.c
./${CURPATH}src/liblzma/common/block_util.c
./${CURPATH}src/liblzma/common/stream_buffer_encoder.c
./${CURPATH}src/liblzma/common/index_hash.c
./${CURPATH}src/liblzma/common/block_buffer_decoder.c
./${CURPATH}src/liblzma/common/stream_flags_decoder.c
./${CURPATH}src/liblzma/common/easy_buffer_encoder.c
./${CURPATH}src/liblzma/common/filter_decoder.c
./${CURPATH}src/liblzma/common/easy_decoder_memusage.c
./${CURPATH}src/liblzma/common/filter_buffer_encoder.c
./${CURPATH}src/liblzma/common/index.c
./${CURPATH}src/liblzma/common/block_decoder.c
./${CURPATH}src/liblzma/common/stream_flags_common.c
./${CURPATH}src/liblzma/common/block_header_decoder.c
./${CURPATH}src/liblzma/common/filter_flags_encoder.c
./${CURPATH}src/liblzma/common/filter_common.c
./${CURPATH}src/liblzma/common/stream_buffer_decoder.c
./${CURPATH}src/liblzma/common/easy_encoder_memusage.c
./${CURPATH}src/liblzma/common/easy_encoder.c
./${CURPATH}src/liblzma/common/common.c
./${CURPATH}src/liblzma/common/index_decoder.c
./${CURPATH}src/liblzma/common/stream_decoder.c
./${CURPATH}src/liblzma/common/vli_decoder.c
./${CURPATH}src/liblzma/common/block_encoder.c
./${CURPATH}src/liblzma/common/vli_encoder.c
./${CURPATH}src/liblzma/common/easy_preset.c
./${CURPATH}src/liblzma/common/filter_flags_decoder.c
./${CURPATH}src/liblzma/simple/simple_coder.c
./${CURPATH}src/liblzma/simple/arm.c
./${CURPATH}src/liblzma/simple/sparc.c
./${CURPATH}src/liblzma/simple/armthumb.c
./${CURPATH}src/liblzma/simple/ia64.c
./${CURPATH}src/liblzma/simple/simple_encoder.c
./${CURPATH}src/liblzma/simple/x86.c
./${CURPATH}src/liblzma/simple/powerpc.c
./${CURPATH}src/liblzma/simple/simple_decoder.c
./${CURPATH}src/liblzma/lzma/lzma_encoder_optimum_fast.c
./${CURPATH}src/liblzma/lzma/fastpos_table.c
./${CURPATH}src/liblzma/lzma/lzma_encoder_presets.c
./${CURPATH}src/liblzma/lzma/lzma_encoder.c
./${CURPATH}src/liblzma/lzma/lzma2_encoder.c
./${CURPATH}src/liblzma/lzma/lzma_decoder.c
./${CURPATH}src/liblzma/lzma/fastpos_tablegen.c
./${CURPATH}src/liblzma/lzma/lzma_encoder_optimum_normal.c
./${CURPATH}src/liblzma/lzma/lzma2_decoder.c
./${CURPATH}src/liblzma/lz/lz_encoder_mf.c
./${CURPATH}src/liblzma/lz/lz_decoder.c
./${CURPATH}src/liblzma/lz/lz_encoder.c
./${CURPATH}src/liblzma/rangecoder/price_table.c
./${CURPATH}src/liblzma/rangecoder/price_tablegen.c
./${CURPATH}src/liblzma/check/check.c
./${CURPATH}src/liblzma/check/crc32_tablegen.c
./${CURPATH}src/liblzma/check/sha256.c
./${CURPATH}src/liblzma/check/crc64_fast.c
./${CURPATH}src/liblzma/check/crc32_fast.c
./${CURPATH}src/liblzma/check/crc64_tablegen.c
./${CURPATH}src/liblzma/check/crc32_small.c
./${CURPATH}src/liblzma/check/crc64_small.c
./${CURPATH}src/liblzma/check/crc32_table.c
./${CURPATH}src/liblzma/check/crc64_table.c
./${CURPATH}src/xz/suffix.c
./${CURPATH}src/xz/options.c
./${CURPATH}src/xz/args.c
./${CURPATH}src/xz/file_io.c
./${CURPATH}src/xz/coder.c
./${CURPATH}src/xz/list.c
./${CURPATH}src/xz/message.c
./${CURPATH}src/xz/hardware.c
./${CURPATH}src/xz/util.c
./${CURPATH}src/xz/signals.c
./${CURPATH}src/xz/main.c
./${CURPATH}src/xzdec/xzdec.c
./${CURPATH}lib/getopt.c
./${CURPATH}lib/getopt1.c
#other see list.txt
)
