SET(OS_CONTRIB_CURL_SRC
./${CURPATH}lib/http_digest.c
./${CURPATH}lib/http_negotiate_sspi.c
./${CURPATH}lib/smtp.c
./${CURPATH}lib/hmac.c
./${CURPATH}lib/fileinfo.c
./${CURPATH}lib/http_proxy.c
./${CURPATH}lib/hostasyn.c
./${CURPATH}lib/curl_ntlm_core.c
./${CURPATH}lib/curl_rand.c
./${CURPATH}lib/inet_ntop.c
./${CURPATH}lib/hostip4.c
./${CURPATH}lib/mprintf.c
./${CURPATH}lib/parsedate.c
./${CURPATH}lib/strerror.c
./${CURPATH}lib/wildcard.c
./${CURPATH}lib/curl_gethostname.c
./${CURPATH}lib/multi.c
./${CURPATH}lib/getinfo.c
./${CURPATH}lib/hostip6.c
./${CURPATH}lib/asyn-thread.c
./${CURPATH}lib/curl_darwinssl.c
./${CURPATH}lib/rawstr.c
./${CURPATH}lib/socks_sspi.c
./${CURPATH}lib/curl_schannel.c
./${CURPATH}lib/timeval.c
./${CURPATH}lib/curl_gssapi.c
./${CURPATH}lib/sendf.c
./${CURPATH}lib/curl_sasl.c
./${CURPATH}lib/non-ascii.c
./${CURPATH}lib/nss.c
./${CURPATH}lib/sslgen.c
./${CURPATH}lib/nwos.c
./${CURPATH}lib/imap.c
./${CURPATH}lib/qssl.c
./${CURPATH}lib/curl_memrchr.c
./${CURPATH}lib/curl_fnmatch.c
./${CURPATH}lib/base64.c
./${CURPATH}lib/formdata.c
./${CURPATH}lib/easy.c
./${CURPATH}lib/curl_ntlm_wb.c
./${CURPATH}lib/cookie.c
./${CURPATH}lib/openldap.c
./${CURPATH}lib/ssluse.c
./${CURPATH}lib/curl_sspi.c
./${CURPATH}lib/curl_ntlm.c
./${CURPATH}lib/krb4.c
./${CURPATH}lib/select.c
./${CURPATH}lib/krb5.c
./${CURPATH}lib/strdup.c
./${CURPATH}lib/socks_gssapi.c
./${CURPATH}lib/warnless.c
./${CURPATH}lib/curl_multibyte.c
./${CURPATH}lib/strequal.c
./${CURPATH}lib/strtoofft.c
./${CURPATH}lib/dict.c
./${CURPATH}lib/curl_ntlm_msgs.c
./${CURPATH}lib/speedcheck.c
./${CURPATH}lib/curl_rtmp.c
./${CURPATH}lib/strtok.c
./${CURPATH}lib/nwlib.c
./${CURPATH}lib/ldap.c
./${CURPATH}lib/gtls.c
./${CURPATH}lib/share.c
./${CURPATH}lib/md4.c
./${CURPATH}lib/curl_addrinfo.c
./${CURPATH}lib/security.c
./${CURPATH}lib/inet_pton.c
./${CURPATH}lib/md5.c
./${CURPATH}lib/amigaos.c
./${CURPATH}lib/connect.c
./${CURPATH}lib/polarssl.c
./${CURPATH}lib/content_encoding.c
./${CURPATH}lib/idn_win32.c
./${CURPATH}lib/version.c
./${CURPATH}lib/llist.c
./${CURPATH}lib/tftp.c
./${CURPATH}lib/nonblock.c
./${CURPATH}lib/http_chunks.c
./${CURPATH}lib/asyn-ares.c
./${CURPATH}lib/http_negotiate.c
./${CURPATH}lib/escape.c
./${CURPATH}lib/file.c
./${CURPATH}lib/slist.c
./${CURPATH}lib/getenv.c
./${CURPATH}lib/axtls.c
./${CURPATH}lib/ftp.c
./${CURPATH}lib/splay.c
./${CURPATH}lib/pingpong.c
./${CURPATH}lib/socks.c
./${CURPATH}lib/rtsp.c
./${CURPATH}lib/telnet.c
./${CURPATH}lib/gopher.c
./${CURPATH}lib/transfer.c
./${CURPATH}lib/pop3.c
./${CURPATH}lib/progress.c
./${CURPATH}lib/hostsyn.c
./${CURPATH}lib/http.c
./${CURPATH}lib/ssh.c
./${CURPATH}lib/hostip.c
./${CURPATH}lib/netrc.c
./${CURPATH}lib/ftplistparser.c
./${CURPATH}lib/url.c
./${CURPATH}lib/if2ip.c
./${CURPATH}lib/cyassl.c
./${CURPATH}lib/hash.c
./${CURPATH}lib/memdebug.c
./${CURPATH}lib/curl_threads.c
)
