SET(OS_LIB_SRC
./prex/syscalls/thread_setpri.c
./prex/syscalls/sem_wait.c
./prex/syscalls/thread_getpri.c
./prex/syscalls/cond_wait.c
./prex/syscalls/timer_waitperiod.c
./prex/syscalls/thread_setpolicy.c
./prex/syscalls/thread_getpolicy.c
./prex/syscalls/mutex_lock.c
#./prex/malloc/malloc_r.c
./prex/malloc/malloc.c
./prex/malloc/realloc.c
./prex/gen/dassert.c
#./prex/gen/panic.c
#./prex/gen/dprintf.c
#./libsa/puts.c
#./libsa/printf.c
#./libsa/putchar.c
./libsa/_stdio.c
#./libsa/vsprintf.c
./crt/crt1.c
./net/lib_inetntop.c
./net/lib_htonl.c
./net/lib_htons.c
./net/lib_inetntoa.c
./net/lib_inetaddr.c
./net/lib_etherntoa.c
./net/lib_inetpton.c
./libm/cosh.c
./libm/acosh.c
./libm/j1.c
./libm/remainder.c
./libm/hypot.c
./libm/sqrt.c
./libm/gamma_r.c
./libm/atanh.c
./libm/exp.c
./libm/k_sin.c
./libm/acos.c
./libm/atan2.c
./libm/j0.c
./libm/fmod.c
./libm/rem_pio2.c
./libm/drem.c
./libm/k_rem_pio2.c
./libm/log.c
./libm/sinh.c
./libm/lgamma.c
./libm/pow.c
./libm/k_tan.c
./libm/jn.c
./libm/log2.c
./libm/gamma.c
./libm/exp2.c
./libm/cbrt.c
./libm/log10.c
./libm/atan.c
./libm/lgamma_r.c
./libm/asin.c
./libm/k_cos.c
#./libm/temp-support.c
./libm/scalb.c
./posix/time/gettimeofday.c
#./posix/process/getpid.c
./posix/process/getpgrp.c
./posix/process/getgid.c
#./posix/process/getpgid.c
./posix/process/setgid.c
#./posix/process/getppid.c
./posix/process/setpgrp.c
./posix/process/killpg.c
./posix/process/seteuid.c
#./posix/process/kill.c
#./posix/process/fork_nommu.c
#./posix/process/getsid.c
#./posix/process/setpgid.c
./posix/process/__process.c
./posix/process/nice.c
#./posix/process/setsid.c
./posix/process/geteuid.c
#./posix/process/getpriority.c
./posix/process/_exit.c
./posix/process/wait.c
#./posix/process/waitpid.c
./posix/process/getegid.c
#./posix/process/fork.c
./posix/process/setuid.c
./posix/process/sleep.c
./posix/process/setegid.c
./posix/process/getuid.c
#./posix/process/setpriority.c
#./posix/gen/uname.c
#./posix/gen/alarm.c
./posix/gen/getrlimit.c
./posix/gen/__posix_init.c
./posix/gen/__posix_call.c
./posix/gen/syslog.c
./posix/signal/sigaction.c
./posix/signal/pause.c
#./posix/signal/__exception.c
./posix/signal/sigcompat.c
./posix/signal/sigpending.c
./posix/signal/siglist.c
./posix/signal/signal.c
./posix/signal/sigsuspend.c
./posix/signal/sigprocmask.c
./posix/exec/execve.c
./libc/time/gmtime.c
./libc/time/asctime.c
./libc/time/localtime.c
./libc/time/gmtime_r.c
./libc/time/mktime.c
./libc/time/asctime_r.c
./libc/time/strftime.c
./libc/time/localtime_r.c
./libc/termios/tcflush.c
./libc/termios/cfmakeraw.c
./libc/termios/tcsetattr.c
./libc/termios/cfsetospeed.c
./libc/termios/cfsetispeed.c
./libc/termios/tcsetpgrp.c
./libc/termios/tcdrain.c
./libc/termios/tcsendbreak.c
./libc/termios/tcgetattr.c
./libc/termios/tcflow.c
./libc/termios/tcgetpgrp.c
./libc/termios/cfgetospeed.c
./libc/termios/cfgetispeed.c
./libc/termios/cfsetspeed.c
./libc/ctype/isalpha.c
./libc/ctype/isdigit.c
./libc/ctype/isprint.c
./libc/ctype/isgraph.c
./libc/ctype/iscntrl.c
./libc/ctype/isupper.c
./libc/ctype/ispunct.c
./libc/ctype/isspace.c
./libc/ctype/toupper.c
./libc/ctype/isblank.c
./libc/ctype/tolower.c
./libc/ctype/isalnum.c
./libc/ctype/isxdigit.c
./libc/ctype/islower.c
./libc/string/strsep.c
./libc/string/strspn.c
./libc/string/memcpy.c
./libc/string/strlcpy.c
./libc/string/strerror.c
./libc/string/swab.c
./libc/string/strlcat.c
./libc/string/memccpy.c
./libc/string/strtok_r.c
./libc/string/strpbrk.c
./libc/string/strdup.c
./libc/string/memmove.c
./libc/string/strcspn.c
./libc/string/strlen.c
./libc/string/strtok.c
./libc/string/strrchr.c
./libc/string/strncat.c
./libc/string/index.c
./libc/string/bcmp.c
./libc/string/rindex.c
./libc/string/bzero.c
./libc/string/bcopy.c
./libc/string/strmode.c
./libc/string/ffs.c
./libc/string/strcasecmp.c
./libc/string/strcpy.c
./libc/string/memset.c
./libc/string/strcmp.c
./libc/string/strchr.c
./libc/string/strncpy.c
./libc/string/strncmp.c
./libc/string/memchr.c
./libc/string/strcoll.c
./libc/string/strstr.c
./libc/string/strxfrm.c
./libc/string/strcat.c
./libc/string/memcmp.c
./libc/stdio/puts.c
./libc/stdio/printf.c
./libc/stdio/gets.c
./libc/stdio/fprintf.c
./libc/stdio/ftell.c
./libc/stdio/getc.c
./libc/stdio/makebuf.c
./libc/stdio/fileno.c
./libc/stdio/tmpfile.c
./libc/stdio/fread.c
./libc/stdio/findfp.c
./libc/stdio/sscanf.c
./libc/stdio/fgetc.c
./libc/stdio/fgetpos.c
./libc/stdio/perror.c
./libc/stdio/freopen.c
./libc/stdio/setbuf.c
./libc/stdio/fputs.c
./libc/stdio/putc.c
./libc/stdio/putchar.c
./libc/stdio/scanf.c
./libc/stdio/vprintf.c
./libc/stdio/fflush.c
./libc/stdio/fgets.c
./libc/stdio/fdopen.c
./libc/stdio/flags.c
./libc/stdio/fwrite.c
./libc/stdio/fscanf.c
./libc/stdio/stdio.c
./libc/stdio/rewind.c
./libc/stdio/wsetup.c
./libc/stdio/setbuffer.c
./libc/stdio/mktemp.c
./libc/stdio/getchar.c
./libc/stdio/fclose.c
./libc/stdio/vsnprintf.c
./libc/stdio/setvbuf.c
./libc/stdio/fwalk.c
./libc/stdio/ungetc.c
./libc/stdio/getw.c
./libc/stdio/fseek.c
./libc/stdio/fputc.c
./libc/stdio/snprintf.c
./libc/stdio/putw.c
./libc/stdio/vfscanf.c
./libc/stdio/fpurge.c
./libc/stdio/tempnam.c
./libc/stdio/refill.c
./libc/stdio/vscanf.c
./libc/stdio/vsscanf.c
./libc/stdio/fvwrite.c
./libc/stdio/vsprintf.c
./libc/stdio/remove.c
./libc/stdio/fsetpos.c
./libc/stdio/tmpnam.c
./libc/stdio/sprintf.c
./libc/stdio/feof.c
./libc/stdio/clrerr.c
./libc/stdio/ferror.c
./libc/stdio/fopen.c
./libc/stdio/vfprintf.c
./libc/gen/execlp.c
./libc/gen/execvp.c
./libc/gen/warn.c
./libc/gen/assert.c
./libc/gen/basename.c
./libc/gen/gethostname.c
./libc/gen/getprogname.c
./libc/gen/vwarnx.c
./libc/gen/warnx.c
./libc/gen/sethostname.c
./libc/gen/dirname.c
./libc/gen/errx.c
./libc/gen/verrx.c
./libc/gen/vwarn.c
./libc/gen/fts.c
./libc/gen/__libc_init.c
./libc/gen/err.c
./libc/gen/getpagesize.c
./libc/gen/time.c
./libc/gen/execv.c
./libc/gen/execl.c
./libc/gen/setprogname.c
./libc/gen/getpass.c
./libc/gen/execle.c
./libc/gen/confstr.c
./libc/gen/verr.c
#./libc/errno/errno.c
./libc/errno/errlst.c
./libc/stdlib/abort.c
./libc/stdlib/atexit.c
./libc/stdlib/abs.c
./libc/stdlib/rand.c
./libc/stdlib/strtol.c
./libc/stdlib/atof.c
./libc/stdlib/exit.c
./libc/stdlib/getopt.c
./libc/stdlib/random.c
./libc/stdlib/getsubopt.c
./libc/stdlib/atoi.c
./libc/stdlib/setenv.c
./libc/stdlib/strtoul.c
./libc/stdlib/calloc.c
./libc/stdlib/getenv.c
./libc/stdlib/putenv.c
./libc/stdlib/qsort.c
./libc/stdlib/atol.c
./libc/stdlib/div.c
)
