SET(OS_CONTRIB_LIGHTTPD_SRC
./${CURPATH}src/mod_webdav.c
./${CURPATH}src/fdevent_solaris_port.c
./${CURPATH}src/mod_staticfile.c
./${CURPATH}src/buffer.c
./${CURPATH}src/network_linux_sendfile.c
./${CURPATH}src/splaytree.c
./${CURPATH}src/mod_dirlisting.c
./${CURPATH}src/data_config.c
./${CURPATH}src/mod_ssi.c
./${CURPATH}src/connections-glue.c
./${CURPATH}src/fdevent_freebsd_kqueue.c
./${CURPATH}src/crc32.c
./${CURPATH}src/mod_auth.c
./${CURPATH}src/mod_alias.c
./${CURPATH}src/mod_rewrite.c
./${CURPATH}src/proc_open.c
./${CURPATH}src/http-header-glue.c
./${CURPATH}src/request.c
./${CURPATH}src/mod_redirect.c
./${CURPATH}src/mod_extforward.c
./${CURPATH}src/fdevent_libev.c
./${CURPATH}src/fdevent_solaris_devpoll.c
./${CURPATH}src/data_fastcgi.c
./${CURPATH}src/mod_proxy.c
./${CURPATH}src/server.c
./${CURPATH}src/mod_mysql_vhost.c
./${CURPATH}src/data_string.c
./${CURPATH}src/mod_fastcgi.c
./${CURPATH}src/network_writev.c
./${CURPATH}src/data_count.c
./${CURPATH}src/network.c
./${CURPATH}src/array.c
./${CURPATH}src/stat_cache.c
./${CURPATH}src/mod_usertrack.c
./${CURPATH}src/fdevent_select.c
./${CURPATH}src/response.c
./${CURPATH}src/mod_cml_funcs.c
./${CURPATH}src/configfile.c
./${CURPATH}src/http_chunk.c
./${CURPATH}src/mod_status.c
./${CURPATH}src/data_integer.c
./${CURPATH}src/mod_evhost.c
./${CURPATH}src/fdevent_linux_sysepoll.c
./${CURPATH}src/mod_scgi.c
./${CURPATH}src/mod_skeleton.c
./${CURPATH}src/mod_ssi_expr.c
./${CURPATH}src/mod_magnet.c
./${CURPATH}src/configparser.c
./${CURPATH}src/mod_flv_streaming.c
./${CURPATH}src/mod_cml.c
./${CURPATH}src/mod_magnet_cache.c
./${CURPATH}src/stream.c
./${CURPATH}src/mod_evasive.c
./${CURPATH}src/mod_userdir.c
./${CURPATH}src/mod_rrdtool.c
./${CURPATH}src/log.c
./${CURPATH}src/fdevent.c
./${CURPATH}src/network_freebsd_sendfile.c
./${CURPATH}src/mod_ssi_exprparser.c
./${CURPATH}src/chunk.c
./${CURPATH}src/network_openssl.c
./${CURPATH}src/plugin.c
./${CURPATH}src/md5.c
./${CURPATH}src/status_counter.c
./${CURPATH}src/configfile-glue.c
./${CURPATH}src/mod_simple_vhost.c
./${CURPATH}src/mod_compress.c
./${CURPATH}src/etag.c
./${CURPATH}src/mod_secure_download.c
./${CURPATH}src/connections.c
./${CURPATH}src/fdevent_poll.c
./${CURPATH}src/lempar.c
./${CURPATH}src/joblist.c
./${CURPATH}src/mod_access.c
./${CURPATH}src/http_auth.c
./${CURPATH}src/mod_accesslog.c
./${CURPATH}src/mod_trigger_b4_dl.c
./${CURPATH}src/network_write.c
./${CURPATH}src/data_array.c
./${CURPATH}src/mod_cgi.c
./${CURPATH}src/mod_cml_lua.c
./${CURPATH}src/keyvalue.c
./${CURPATH}src/mod_indexfile.c
./${CURPATH}src/mod_expire.c
./${CURPATH}src/network_solaris_sendfilev.c
./${CURPATH}src/lemon.c
./${CURPATH}src/mod_setenv.c
./${CURPATH}src/inet_ntop_cache.c
./${CURPATH}src/lighttpd-angel.c
./${CURPATH}src/bitset.c
#other
#./${CURPATH}tests/fcgi-responder.c
#./${CURPATH}tests/fcgi-auth.c
)
