// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GSTREAMERMM_BASEAUDIOSINK_P_H
#define _GSTREAMERMM_BASEAUDIOSINK_P_H


#include <glibmm/class.h>

namespace Gst
{

class BaseAudioSink_Class : public Glib::Class
{
public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  typedef BaseAudioSink CppObjectType;
  typedef GstBaseAudioSink BaseObjectType;
  typedef GstBaseAudioSinkClass BaseClassType;
  typedef Gst::BaseSink_Class CppClassParent;
  typedef GstBaseSinkClass BaseClassParent;

  friend class BaseAudioSink;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

  const Glib::Class& init();


  static void class_init_function(void* g_class, void* class_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.

  //Callbacks (virtual functions):
  static GstRingBuffer* create_ringbuffer_vfunc_callback(GstBaseAudioSink* self);
};


} // namespace Gst

#include <gstreamermm/private/basesink_p.h>


#endif /* _GSTREAMERMM_BASEAUDIOSINK_P_H */

