// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GSTREAMERMM_BASEAUDIOSRC_P_H
#define _GSTREAMERMM_BASEAUDIOSRC_P_H


#include <glibmm/class.h>

namespace Gst
{

class BaseAudioSrc_Class : public Glib::Class
{
public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  typedef BaseAudioSrc CppObjectType;
  typedef GstBaseAudioSrc BaseObjectType;
  typedef GstBaseAudioSrcClass BaseClassType;
  typedef Gst::PushSrc_Class CppClassParent;
  typedef GstPushSrcClass BaseClassParent;

  friend class BaseAudioSrc;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

  const Glib::Class& init();


  static void class_init_function(void* g_class, void* class_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.

  //Callbacks (virtual functions):
  static GstRingBuffer* create_ringbuffer_vfunc_callback(GstBaseAudioSrc* self);
};


} // namespace Gst

#include <gstreamermm/private/pushsrc_p.h>


#endif /* _GSTREAMERMM_BASEAUDIOSRC_P_H */

