// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GSTREAMERMM_INDEX_P_H
#define _GSTREAMERMM_INDEX_P_H


#include <glibmm/class.h>

namespace Gst
{

class Index_Class : public Glib::Class
{
public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  typedef Index CppObjectType;
  typedef GstIndex BaseObjectType;
  typedef GstIndexClass BaseClassType;
  typedef Object_Class CppClassParent;
  typedef GstObjectClass BaseClassParent;

  friend class Index;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

  const Glib::Class& init();


  static void class_init_function(void* g_class, void* class_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.
  static void entry_added_callback(GstIndex* self, GstIndexEntry* p0);

  //Callbacks (virtual functions):
  static gboolean get_writer_id_vfunc_callback(GstIndex* self, gint* writer_id, gchar* writer_string);
  static void commit_vfunc_callback(GstIndex* self, gint id);
  static void add_entry_vfunc_callback(GstIndex* self, GstIndexEntry* entry);
  };


} // namespace Gst

#include <gstreamermm/private/object_p.h>


#endif /* _GSTREAMERMM_INDEX_P_H */

