// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GSTREAMERMM_PADTEMPLATE_P_H
#define _GSTREAMERMM_PADTEMPLATE_P_H


#include <glibmm/class.h>

namespace Gst
{

class PadTemplate_Class : public Glib::Class
{
public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  typedef PadTemplate CppObjectType;
  typedef GstPadTemplate BaseObjectType;
  typedef GstPadTemplateClass BaseClassType;
  typedef Object_Class CppClassParent;
  typedef GstObjectClass BaseClassParent;

  friend class PadTemplate;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

  const Glib::Class& init();


  static void class_init_function(void* g_class, void* class_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.
  static void pad_created_callback(GstPadTemplate* self, GstPad* p0);

  //Callbacks (virtual functions):
};


} // namespace Gst

#include <glibmm/private/object_p.h>
#include <gstreamermm/private/object_p.h>


#endif /* _GSTREAMERMM_PADTEMPLATE_P_H */

