// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GSTREAMERMM_XML_P_H
#define _GSTREAMERMM_XML_P_H


#include <glibmm/class.h>

namespace Gst
{

class XML_Class : public Glib::Class
{
public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  typedef XML CppObjectType;
  typedef GstXML BaseObjectType;
  typedef GstXMLClass BaseClassType;
  typedef Object_Class CppClassParent;
  typedef GstObjectClass BaseClassParent;

  friend class XML;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

  const Glib::Class& init();


  static void class_init_function(void* g_class, void* class_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.
  static void object_loaded_callback(GstXML* self, GstObject* p0, xmlNodePtr p1);

  //Callbacks (virtual functions):
};


} // namespace Gst

#include <glibmm/private/object_p.h>
#include <gstreamermm/private/object_p.h>


#endif /* _GSTREAMERMM_XML_P_H */

