// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GSTREAMERMM_ALSAMIXER_H
#define _GSTREAMERMM_ALSAMIXER_H


#include <glibmm.h>

// Generated by generate_plugin_gmmproc_file. Don't edit this file.


#include <gstreamermm/element.h>
#include <gstreamermm/interface.h>
#include <gstreamermm/mixer.h>
#include <gstreamermm/propertyprobe.h>


#ifndef DOXYGEN_SHOULD_SKIP_THIS
typedef struct _GstAlsaMixerElement GstAlsaMixerElement;
typedef struct _GstAlsaMixerElementClass GstAlsaMixerElementClass;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */


namespace Gst
{ class AlsaMixer_Class; } // namespace Gst
namespace Gst
{

/** A Wrapper for the alsamixer plugin.
 * Please note that, though using the underlying GObject is fine, using its C
 * <B>type</B> is not guaranteed to be API stable across releases because it is
 * not guaranteed to always remain the same.  Also, not all plug-ins are
 * available on all systems so care must be taken that they exist before they
 * are used, otherwise there will be errors and possibly a crash.
 *
 * @ingroup GstPlugins
 */

class AlsaMixer
: public Gst::Element, public Gst::Interface, public Gst::Mixer, public Gst::PropertyProbe
{
  
#ifndef DOXYGEN_SHOULD_SKIP_THIS

public:
  typedef AlsaMixer CppObjectType;
  typedef AlsaMixer_Class CppClassType;
  typedef GstAlsaMixerElement BaseObjectType;
  typedef GstAlsaMixerElementClass BaseClassType;

private:  friend class AlsaMixer_Class;
  static CppClassType alsamixer_class_;

private:
  // noncopyable
  AlsaMixer(const AlsaMixer&);
  AlsaMixer& operator=(const AlsaMixer&);

protected:
  explicit AlsaMixer(const Glib::ConstructParams& construct_params);
  explicit AlsaMixer(GstAlsaMixerElement* castitem);

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

public:
  virtual ~AlsaMixer();

#ifndef DOXYGEN_SHOULD_SKIP_THIS
  static GType get_type()      G_GNUC_CONST;


  static GType get_base_type() G_GNUC_CONST;
#endif

  ///Provides access to the underlying C GObject.
  GstAlsaMixerElement*       gobj()       { return reinterpret_cast<GstAlsaMixerElement*>(gobject_); }

  ///Provides access to the underlying C GObject.
  const GstAlsaMixerElement* gobj() const { return reinterpret_cast<GstAlsaMixerElement*>(gobject_); }

  ///Provides access to the underlying C instance. The caller is responsible for unrefing it. Use when directly setting fields in structs.
  GstAlsaMixerElement* gobj_copy();

private:

  
protected:
  AlsaMixer();
  explicit AlsaMixer(const Glib::ustring& name);

public:
  /** Creates a new alsamixer plugin with a unique name.
   */
  
  static Glib::RefPtr<AlsaMixer> create();


  /** Creates a new alsamixer plugin with the given name.
   */
  
  static Glib::RefPtr<AlsaMixer> create(const Glib::ustring& name);


  #ifdef GLIBMM_PROPERTIES_ENABLED
/** ALSA device, as defined in an asound configuration file.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy<Glib::ustring> property_device() ;
#endif //#GLIBMM_PROPERTIES_ENABLED

#ifdef GLIBMM_PROPERTIES_ENABLED
/** ALSA device, as defined in an asound configuration file.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly<Glib::ustring> property_device() const;
#endif //#GLIBMM_PROPERTIES_ENABLED

  #ifdef GLIBMM_PROPERTIES_ENABLED
/** Human-readable name of the sound device.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly<Glib::ustring> property_device_name() const;
#endif //#GLIBMM_PROPERTIES_ENABLED


public:

public:
  //C++ methods used to invoke GTK+ virtual functions:

protected:
  //GTK+ Virtual Functions (override these to change behaviour):

  //Default Signal Handlers::


};

} // namespace Gst


namespace Glib
{
  /** A Glib::wrap() method for this object.
   * 
   * @param object The C instance.
   * @param take_copy False if the result should take ownership of the C instance. True if it should take a new copy or ref.
   * @result A C++ instance that wraps this C instance.
   *
   * @relates Gst::AlsaMixer
   */
  Glib::RefPtr<Gst::AlsaMixer> wrap(GstAlsaMixerElement* object, bool take_copy = false);
}


#endif /* _GSTREAMERMM_ALSAMIXER_H */

