// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GSTREAMERMM_CLOCKOVERLAY_H
#define _GSTREAMERMM_CLOCKOVERLAY_H


#include <glibmm.h>

// Generated by generate_plugin_gmmproc_file. Don't edit this file.


#include <gstreamermm/textoverlay.h>


#ifndef DOXYGEN_SHOULD_SKIP_THIS
typedef struct _GstClockOverlay GstClockOverlay;
typedef struct _GstClockOverlayClass GstClockOverlayClass;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */


namespace Gst
{ class ClockOverlay_Class; } // namespace Gst
namespace Gst
{

/** A Wrapper for the clockoverlay plugin.
 * Please note that, though using the underlying GObject is fine, using its C
 * <B>type</B> is not guaranteed to be API stable across releases because it is
 * not guaranteed to always remain the same.  Also, not all plug-ins are
 * available on all systems so care must be taken that they exist before they
 * are used, otherwise there will be errors and possibly a crash.
 *
 * @ingroup GstPlugins
 */

class ClockOverlay
: public Gst::TextOverlay
{
  
#ifndef DOXYGEN_SHOULD_SKIP_THIS

public:
  typedef ClockOverlay CppObjectType;
  typedef ClockOverlay_Class CppClassType;
  typedef GstClockOverlay BaseObjectType;
  typedef GstClockOverlayClass BaseClassType;

private:  friend class ClockOverlay_Class;
  static CppClassType clockoverlay_class_;

private:
  // noncopyable
  ClockOverlay(const ClockOverlay&);
  ClockOverlay& operator=(const ClockOverlay&);

protected:
  explicit ClockOverlay(const Glib::ConstructParams& construct_params);
  explicit ClockOverlay(GstClockOverlay* castitem);

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

public:
  virtual ~ClockOverlay();

#ifndef DOXYGEN_SHOULD_SKIP_THIS
  static GType get_type()      G_GNUC_CONST;


  static GType get_base_type() G_GNUC_CONST;
#endif

  ///Provides access to the underlying C GObject.
  GstClockOverlay*       gobj()       { return reinterpret_cast<GstClockOverlay*>(gobject_); }

  ///Provides access to the underlying C GObject.
  const GstClockOverlay* gobj() const { return reinterpret_cast<GstClockOverlay*>(gobject_); }

  ///Provides access to the underlying C instance. The caller is responsible for unrefing it. Use when directly setting fields in structs.
  GstClockOverlay* gobj_copy();

private:

  
protected:
  ClockOverlay();
  explicit ClockOverlay(const Glib::ustring& name);

public:
  /** Creates a new clockoverlay plugin with a unique name.
   */
  
  static Glib::RefPtr<ClockOverlay> create();


  /** Creates a new clockoverlay plugin with the given name.
   */
  
  static Glib::RefPtr<ClockOverlay> create(const Glib::ustring& name);


  #ifdef GLIBMM_PROPERTIES_ENABLED
/** Format to use for time and date value, as in strftime.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy<Glib::ustring> property_time_format() ;
#endif //#GLIBMM_PROPERTIES_ENABLED

#ifdef GLIBMM_PROPERTIES_ENABLED
/** Format to use for time and date value, as in strftime.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly<Glib::ustring> property_time_format() const;
#endif //#GLIBMM_PROPERTIES_ENABLED


public:

public:
  //C++ methods used to invoke GTK+ virtual functions:

protected:
  //GTK+ Virtual Functions (override these to change behaviour):

  //Default Signal Handlers::


};

} // namespace Gst


namespace Glib
{
  /** A Glib::wrap() method for this object.
   * 
   * @param object The C instance.
   * @param take_copy False if the result should take ownership of the C instance. True if it should take a new copy or ref.
   * @result A C++ instance that wraps this C instance.
   *
   * @relates Gst::ClockOverlay
   */
  Glib::RefPtr<Gst::ClockOverlay> wrap(GstClockOverlay* object, bool take_copy = false);
}


#endif /* _GSTREAMERMM_CLOCKOVERLAY_H */

