// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GSTREAMERMM_OGGDEMUX_H
#define _GSTREAMERMM_OGGDEMUX_H


#include <glibmm.h>

// Generated by generate_plugin_gmmproc_file. Don't edit this file.


#include <gstreamermm/element.h>


#ifndef DOXYGEN_SHOULD_SKIP_THIS
typedef struct _GstOggDemux GstOggDemux;
typedef struct _GstOggDemuxClass GstOggDemuxClass;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */


namespace Gst
{ class OggDemux_Class; } // namespace Gst
namespace Gst
{

/** A Wrapper for the oggdemux plugin.
 * Please note that, though using the underlying GObject is fine, using its C
 * <B>type</B> is not guaranteed to be API stable across releases because it is
 * not guaranteed to always remain the same.  Also, not all plug-ins are
 * available on all systems so care must be taken that they exist before they
 * are used, otherwise there will be errors and possibly a crash.
 *
 * @ingroup GstPlugins
 */

class OggDemux
: public Gst::Element
{
  
#ifndef DOXYGEN_SHOULD_SKIP_THIS

public:
  typedef OggDemux CppObjectType;
  typedef OggDemux_Class CppClassType;
  typedef GstOggDemux BaseObjectType;
  typedef GstOggDemuxClass BaseClassType;

private:  friend class OggDemux_Class;
  static CppClassType oggdemux_class_;

private:
  // noncopyable
  OggDemux(const OggDemux&);
  OggDemux& operator=(const OggDemux&);

protected:
  explicit OggDemux(const Glib::ConstructParams& construct_params);
  explicit OggDemux(GstOggDemux* castitem);

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

public:
  virtual ~OggDemux();

#ifndef DOXYGEN_SHOULD_SKIP_THIS
  static GType get_type()      G_GNUC_CONST;


  static GType get_base_type() G_GNUC_CONST;
#endif

  ///Provides access to the underlying C GObject.
  GstOggDemux*       gobj()       { return reinterpret_cast<GstOggDemux*>(gobject_); }

  ///Provides access to the underlying C GObject.
  const GstOggDemux* gobj() const { return reinterpret_cast<GstOggDemux*>(gobject_); }

  ///Provides access to the underlying C instance. The caller is responsible for unrefing it. Use when directly setting fields in structs.
  GstOggDemux* gobj_copy();

private:

  
protected:
  OggDemux();
  explicit OggDemux(const Glib::ustring& name);

public:
  /** Creates a new oggdemux plugin with a unique name.
   */
  
  static Glib::RefPtr<OggDemux> create();


  /** Creates a new oggdemux plugin with the given name.
   */
  
  static Glib::RefPtr<OggDemux> create(const Glib::ustring& name);


public:

public:
  //C++ methods used to invoke GTK+ virtual functions:

protected:
  //GTK+ Virtual Functions (override these to change behaviour):

  //Default Signal Handlers::


};

} // namespace Gst


namespace Glib
{
  /** A Glib::wrap() method for this object.
   * 
   * @param object The C instance.
   * @param take_copy False if the result should take ownership of the C instance. True if it should take a new copy or ref.
   * @result A C++ instance that wraps this C instance.
   *
   * @relates Gst::OggDemux
   */
  Glib::RefPtr<Gst::OggDemux> wrap(GstOggDemux* object, bool take_copy = false);
}


#endif /* _GSTREAMERMM_OGGDEMUX_H */

