// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GSTREAMERMM_THEORAPARSE_H
#define _GSTREAMERMM_THEORAPARSE_H


#include <glibmm.h>

// Generated by generate_plugin_gmmproc_file. Don't edit this file.


#include <gstreamermm/element.h>
#include <glibmm/valuearray.h>


#ifndef DOXYGEN_SHOULD_SKIP_THIS
typedef struct _GstTheoraParse GstTheoraParse;
typedef struct _GstTheoraParseClass GstTheoraParseClass;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */


namespace Gst
{ class TheoraParse_Class; } // namespace Gst
namespace Gst
{

/** A Wrapper for the theoraparse plugin.
 * Please note that, though using the underlying GObject is fine, using its C
 * <B>type</B> is not guaranteed to be API stable across releases because it is
 * not guaranteed to always remain the same.  Also, not all plug-ins are
 * available on all systems so care must be taken that they exist before they
 * are used, otherwise there will be errors and possibly a crash.
 *
 * @ingroup GstPlugins
 */

class TheoraParse
: public Gst::Element
{
  
#ifndef DOXYGEN_SHOULD_SKIP_THIS

public:
  typedef TheoraParse CppObjectType;
  typedef TheoraParse_Class CppClassType;
  typedef GstTheoraParse BaseObjectType;
  typedef GstTheoraParseClass BaseClassType;

private:  friend class TheoraParse_Class;
  static CppClassType theoraparse_class_;

private:
  // noncopyable
  TheoraParse(const TheoraParse&);
  TheoraParse& operator=(const TheoraParse&);

protected:
  explicit TheoraParse(const Glib::ConstructParams& construct_params);
  explicit TheoraParse(GstTheoraParse* castitem);

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

public:
  virtual ~TheoraParse();

#ifndef DOXYGEN_SHOULD_SKIP_THIS
  static GType get_type()      G_GNUC_CONST;


  static GType get_base_type() G_GNUC_CONST;
#endif

  ///Provides access to the underlying C GObject.
  GstTheoraParse*       gobj()       { return reinterpret_cast<GstTheoraParse*>(gobject_); }

  ///Provides access to the underlying C GObject.
  const GstTheoraParse* gobj() const { return reinterpret_cast<GstTheoraParse*>(gobject_); }

  ///Provides access to the underlying C instance. The caller is responsible for unrefing it. Use when directly setting fields in structs.
  GstTheoraParse* gobj_copy();

private:

  
protected:
  TheoraParse();
  explicit TheoraParse(const Glib::ustring& name);

public:
  /** Creates a new theoraparse plugin with a unique name.
   */
  
  static Glib::RefPtr<TheoraParse> create();


  /** Creates a new theoraparse plugin with the given name.
   */
  
  static Glib::RefPtr<TheoraParse> create(const Glib::ustring& name);


  #ifdef GLIBMM_PROPERTIES_ENABLED
/** An array of (granuletime, buffertime) pairs.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy<Glib::ValueArray> property_synchronization_points() ;
#endif //#GLIBMM_PROPERTIES_ENABLED

#ifdef GLIBMM_PROPERTIES_ENABLED
/** An array of (granuletime, buffertime) pairs.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly<Glib::ValueArray> property_synchronization_points() const;
#endif //#GLIBMM_PROPERTIES_ENABLED


public:

public:
  //C++ methods used to invoke GTK+ virtual functions:

protected:
  //GTK+ Virtual Functions (override these to change behaviour):

  //Default Signal Handlers::


};

} // namespace Gst


namespace Glib
{
  /** A Glib::wrap() method for this object.
   * 
   * @param object The C instance.
   * @param take_copy False if the result should take ownership of the C instance. True if it should take a new copy or ref.
   * @result A C++ instance that wraps this C instance.
   *
   * @relates Gst::TheoraParse
   */
  Glib::RefPtr<Gst::TheoraParse> wrap(GstTheoraParse* object, bool take_copy = false);
}


#endif /* _GSTREAMERMM_THEORAPARSE_H */

