// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GSTREAMERMM_VIDEOSCALE_H
#define _GSTREAMERMM_VIDEOSCALE_H


#include <glibmm.h>

// Generated by generate_plugin_gmmproc_file. Don't edit this file.


#include <gstreamermm/basetransform.h>


#ifndef DOXYGEN_SHOULD_SKIP_THIS
typedef struct _GstVideoScale GstVideoScale;
typedef struct _GstVideoScaleClass GstVideoScaleClass;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */


namespace Gst
{ class VideoScale_Class; } // namespace Gst
namespace Gst
{

/** @addtogroup gstreamermmEnums gstreamermm Enums and Flags */

/**
 * @ingroup gstreamermmEnums
 */
enum VideoScaleMethod
{
  VIDEO_SCALE_NEAREST,
  VIDEO_SCALE_BILINEAR,
  VIDEO_SCALE_4TAP
};

} // namespace Gst


#ifndef DOXYGEN_SHOULD_SKIP_THIS
namespace Glib
{

template <>
class Value<Gst::VideoScaleMethod> : public Glib::Value_Enum<Gst::VideoScaleMethod>
{
public:
  static GType value_type() G_GNUC_CONST;
};

} // namespace Glib
#endif /* DOXYGEN_SHOULD_SKIP_THIS */


namespace Gst
{


/** A Wrapper for the videoscale plugin.
 * Please note that, though using the underlying GObject is fine, using its C
 * <B>type</B> is not guaranteed to be API stable across releases because it is
 * not guaranteed to always remain the same.  Also, not all plug-ins are
 * available on all systems so care must be taken that they exist before they
 * are used, otherwise there will be errors and possibly a crash.
 *
 * @ingroup GstPlugins
 */

class VideoScale
: public Gst::BaseTransform
{
  
#ifndef DOXYGEN_SHOULD_SKIP_THIS

public:
  typedef VideoScale CppObjectType;
  typedef VideoScale_Class CppClassType;
  typedef GstVideoScale BaseObjectType;
  typedef GstVideoScaleClass BaseClassType;

private:  friend class VideoScale_Class;
  static CppClassType videoscale_class_;

private:
  // noncopyable
  VideoScale(const VideoScale&);
  VideoScale& operator=(const VideoScale&);

protected:
  explicit VideoScale(const Glib::ConstructParams& construct_params);
  explicit VideoScale(GstVideoScale* castitem);

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

public:
  virtual ~VideoScale();

#ifndef DOXYGEN_SHOULD_SKIP_THIS
  static GType get_type()      G_GNUC_CONST;


  static GType get_base_type() G_GNUC_CONST;
#endif

  ///Provides access to the underlying C GObject.
  GstVideoScale*       gobj()       { return reinterpret_cast<GstVideoScale*>(gobject_); }

  ///Provides access to the underlying C GObject.
  const GstVideoScale* gobj() const { return reinterpret_cast<GstVideoScale*>(gobject_); }

  ///Provides access to the underlying C instance. The caller is responsible for unrefing it. Use when directly setting fields in structs.
  GstVideoScale* gobj_copy();

private:

  
protected:
  VideoScale();
  explicit VideoScale(const Glib::ustring& name);

public:
  /** Creates a new videoscale plugin with a unique name.
   */
  
  static Glib::RefPtr<VideoScale> create();


  /** Creates a new videoscale plugin with the given name.
   */
  
  static Glib::RefPtr<VideoScale> create(const Glib::ustring& name);


  #ifdef GLIBMM_PROPERTIES_ENABLED
/** method.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy<Gst::VideoScaleMethod> property_method() ;
#endif //#GLIBMM_PROPERTIES_ENABLED

#ifdef GLIBMM_PROPERTIES_ENABLED
/** method.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly<Gst::VideoScaleMethod> property_method() const;
#endif //#GLIBMM_PROPERTIES_ENABLED

  #ifdef GLIBMM_PROPERTIES_ENABLED
/** Add black borders if necessary to keep the display aspect ratio.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy<bool> property_add_borders() ;
#endif //#GLIBMM_PROPERTIES_ENABLED

#ifdef GLIBMM_PROPERTIES_ENABLED
/** Add black borders if necessary to keep the display aspect ratio.
   *
   * You rarely need to use properties because there are get_ and set_ methods for almost all of them.
   * @return A PropertyProxy that allows you to get or set the property of the value, or receive notification when
   * the value of the property changes.
   */
  Glib::PropertyProxy_ReadOnly<bool> property_add_borders() const;
#endif //#GLIBMM_PROPERTIES_ENABLED


public:

public:
  //C++ methods used to invoke GTK+ virtual functions:

protected:
  //GTK+ Virtual Functions (override these to change behaviour):

  //Default Signal Handlers::


};

} // namespace Gst


namespace Glib
{
  /** A Glib::wrap() method for this object.
   * 
   * @param object The C instance.
   * @param take_copy False if the result should take ownership of the C instance. True if it should take a new copy or ref.
   * @result A C++ instance that wraps this C instance.
   *
   * @relates Gst::VideoScale
   */
  Glib::RefPtr<Gst::VideoScale> wrap(GstVideoScale* object, bool take_copy = false);
}


#endif /* _GSTREAMERMM_VIDEOSCALE_H */

