SET(OS_CONTRIB_LIBSOUP_SRC
./${CURPATH}libsoup/soup-cookie-jar-sqlite.c
./${CURPATH}libsoup/soup-multipart.c
./${CURPATH}libsoup/soup-body-input-stream.c
./${CURPATH}libsoup/soup-headers.c
./${CURPATH}libsoup/soup-session.c
./${CURPATH}libsoup/soup-server.c
./${CURPATH}libsoup/soup-message-client-io.c
./${CURPATH}libsoup/soup-logger.c
./${CURPATH}libsoup/soup-request.c
./${CURPATH}libsoup/soup-client-input-stream.c
./${CURPATH}libsoup/soup-cookie-jar-text.c
./${CURPATH}libsoup/soup-method.c
./${CURPATH}libsoup/soup-request-http.c
./${CURPATH}libsoup/soup-password-manager.c
./${CURPATH}libsoup/soup-auth-basic.c
./${CURPATH}libsoup/soup-session-feature.c
./${CURPATH}libsoup/soup-proxy-resolver-gnome.c
./${CURPATH}libsoup/soup-date.c
./${CURPATH}libsoup/soup-message-server-io.c
./${CURPATH}libsoup/soup-value-utils.c
./${CURPATH}libsoup/soup-tld.c
./${CURPATH}libsoup/soup-auth-domain.c
./${CURPATH}libsoup/soup-uri.c
./${CURPATH}libsoup/soup-marshal.c
./${CURPATH}libsoup/soup-auth-domain-digest.c
./${CURPATH}libsoup/soup-form.c
./${CURPATH}libsoup/soup-gnome-features.c
./${CURPATH}libsoup/soup-filter-input-stream.c
./${CURPATH}libsoup/soup-request-file.c
./${CURPATH}libsoup/soup-xmlrpc.c
./${CURPATH}libsoup/soup-socket.c
./${CURPATH}libsoup/soup-message-body.c
./${CURPATH}libsoup/soup-status.c
./${CURPATH}libsoup/soup-proxy-resolver-default.c
./${CURPATH}libsoup/soup-enum-types.c
./${CURPATH}libsoup/soup-cache.c
./${CURPATH}libsoup/soup-multipart-input-stream.c
./${CURPATH}libsoup/soup-auth.c
./${CURPATH}libsoup/soup-session-sync.c
./${CURPATH}libsoup/soup-content-decoder.c
./${CURPATH}libsoup/soup-requester.c
./${CURPATH}libsoup/soup-address.c
./${CURPATH}libsoup/soup-proxy-resolver-static.c
./${CURPATH}libsoup/soup-content-sniffer.c
./${CURPATH}libsoup/soup-proxy-resolver.c
./${CURPATH}libsoup/soup-password-manager-gnome.c
./${CURPATH}libsoup/soup-directory-input-stream.c
./${CURPATH}libsoup/soup-cookie-jar.c
./${CURPATH}libsoup/soup-path-map.c
./${CURPATH}libsoup/soup-message-io.c
./${CURPATH}libsoup/soup-connection.c
./${CURPATH}libsoup/soup-message.c
./${CURPATH}libsoup/soup-content-sniffer-stream.c
./${CURPATH}libsoup/soup-auth-manager.c
./${CURPATH}libsoup/soup-auth-ntlm.c
./${CURPATH}libsoup/soup-message-queue.c
./${CURPATH}libsoup/soup-misc.c
./${CURPATH}libsoup/soup-auth-domain-basic.c
./${CURPATH}libsoup/soup-auth-manager-ntlm.c
./${CURPATH}libsoup/soup-io-stream.c
./${CURPATH}libsoup/soup-message-headers.c
./${CURPATH}libsoup/soup-request-data.c
./${CURPATH}libsoup/soup-body-output-stream.c
./${CURPATH}libsoup/soup-session-async.c
./${CURPATH}libsoup/soup-auth-digest.c
./${CURPATH}libsoup/soup-converter-wrapper.c
./${CURPATH}libsoup/soup-proxy-uri-resolver.c
./${CURPATH}libsoup/soup-cookie.c
)
