SET(OS_CONTRIB_PHP_SRC
./stub.c
./TSRM/TSRM.c
./main/php_ticks.c
./main/internal_functions.c
./main/strlcpy.c
./main/php_logos.c
./main/strlcat.c
./main/php_scandir.c
./main/streams/memory.c
./main/streams/transports.c
./main/streams/cast.c
./main/streams/filter.c
./main/streams/plain_wrapper.c
./main/streams/userspace.c
./main/streams/mmap.c
./main/streams/streams.c
./main/streams/xp_socket.c
./main/streams/glob_wrapper.c
./main/safe_mode.c
./main/fopen_wrappers.c
./main/output.c
./main/network.c
./main/getopt.c
./main/php_content_types.c
./main/rfc1867.c
./main/php_ini.c
./main/snprintf.c
./main/alloca.c
#./main/internal_functions_cli.c
./main/reentrancy.c
./main/php_variables.c
./main/mergesort.c
./main/SAPI.c
./main/spprintf.c
./main/php_open_temporary_file.c
./main/php_sprintf.c
./main/main.c
./ext/zlib/zlib_fopen_wrapper.c
./ext/zlib/zlib_filter.c
./ext/zlib/zlib.c
./ext/xml/xml.c
./ext/xml/compat.c
./ext/gettext/gettext.c
./ext/standard/user_filters.c
./ext/standard/pack.c
./ext/standard/fsock.c
./ext/standard/crypt_freesec.c
./ext/standard/var.c
./ext/standard/assert.c
./ext/standard/string.c
./ext/standard/lcg.c
./ext/standard/uuencode.c
./ext/standard/crc32.c
./ext/standard/credits.c
./ext/standard/proc_open.c
./ext/standard/link.c
./ext/standard/mail.c
./ext/standard/info.c
./ext/standard/iptc.c
./ext/standard/versioning.c
./ext/standard/browscap.c
./ext/standard/metaphone.c
./ext/standard/basic_functions.c
./ext/standard/base64.c
./ext/standard/scanf.c
./ext/standard/strnatcmp.c
./ext/standard/uniqid.c
./ext/standard/incomplete_class.c
./ext/standard/soundex.c
./ext/standard/microtime.c
./ext/standard/array.c
./ext/standard/rand.c
./ext/standard/datetime.c
./ext/standard/css.c
./ext/standard/crypt_blowfish.c
./ext/standard/cyr_convert.c
./ext/standard/head.c
./ext/standard/math.c
./ext/standard/syslog.c
./ext/standard/ftp_fopen_wrapper.c
./ext/standard/crypt.c
./ext/standard/dns.c
./ext/standard/php_fopen_wrapper.c
./ext/standard/crypt_sha512.c
./ext/standard/formatted_print.c
./ext/standard/md5.c
./ext/standard/pageinfo.c
./ext/standard/exec.c
./ext/standard/dl.c
./ext/standard/http_fopen_wrapper.c
./ext/standard/ftok.c
./ext/standard/streamsfuncs.c
./ext/standard/sha1.c
./ext/standard/file.c
./ext/standard/levenshtein.c
./ext/standard/filestat.c
./ext/standard/image.c
./ext/standard/php_crypt_r.c
./ext/standard/crypt_sha256.c
./ext/standard/var_unserializer.c
./ext/standard/html.c
./ext/standard/flock_compat.c
./ext/standard/http.c
./ext/standard/quot_print.c
./ext/standard/url_scanner_ex.c
./ext/standard/link_win32.c
./ext/standard/dir.c
./ext/standard/type.c
./ext/standard/filters.c
./ext/standard/url.c
./ext/session/session.c
./ext/session/mod_user.c
./ext/session/mod_mm.c
./ext/session/mod_files.c
./ext/json/utf8_decode.c
./ext/json/json.c
./ext/json/JSON_parser.c
./ext/json/utf8_to_utf16.c
./ext/sysvshm/sysvshm.c
./ext/zip/php_zip.c
./ext/zip/zip_stream.c
./ext/zip/lib/zip_source_crc.c
./ext/zip/lib/zip_get_compression_implementation.c
./ext/zip/lib/zip_source_read.c
./ext/zip/lib/zip_error_get.c
./ext/zip/lib/zip_fdopen.c
./ext/zip/lib/zip_add.c
./ext/zip/lib/zip_stat_index.c
./ext/zip/lib/zip_close.c
./ext/zip/lib/zip_fopen_encrypted.c
./ext/zip/lib/zip_entry_new.c
./ext/zip/lib/zip_set_name.c
./ext/zip/lib/zip_delete.c
./ext/zip/lib/zip_free.c
./ext/zip/lib/zip_source_error.c
./ext/zip/lib/zip_strerror.c
./ext/zip/lib/zip_fopen_index.c
./ext/zip/lib/zip_entry_free.c
./ext/zip/lib/zip_fclose.c
./ext/zip/lib/zip_source_filep.c
./ext/zip/lib/zip_get_archive_flag.c
./ext/zip/lib/zip_set_file_comment.c
./ext/zip/lib/zip_get_num_files.c
./ext/zip/lib/zip_source_layered.c
./ext/zip/lib/zip_get_encryption_implementation.c
./ext/zip/lib/zip_fopen_index_encrypted.c
./ext/zip/lib/zip_unchange_data.c
./ext/zip/lib/zip_set_file_extra.c
./ext/zip/lib/zip_file_get_offset.c
./ext/zip/lib/zip_fopen.c
./ext/zip/lib/zip_dirent.c
./ext/zip/lib/zip_source_function.c
./ext/zip/lib/zip_stat_init.c
./ext/zip/lib/zip_new.c
./ext/zip/lib/zip_error_get_sys_type.c
./ext/zip/lib/zip_source_stat.c
./ext/zip/lib/zip_get_file_extra.c
./ext/zip/lib/zip_source_free.c
./ext/zip/lib/zip_error_clear.c
./ext/zip/lib/zip_unchange_all.c
./ext/zip/lib/zip_source_deflate.c
./ext/zip/lib/zip_replace.c
./ext/zip/lib/zip_file_error_get.c
./ext/zip/lib/zip_stat.c
./ext/zip/lib/zip_fread.c
./ext/zip/lib/zip_set_archive_flag.c
./ext/zip/lib/zip_source_pkware.c
./ext/zip/lib/zip_get_num_entries.c
./ext/zip/lib/zip_source_zip.c
./ext/zip/lib/zip_source_buffer.c
./ext/zip/lib/zip_file_strerror.c
./ext/zip/lib/zip_error_strerror.c
./ext/zip/lib/zip_name_locate.c
./ext/zip/lib/zip_get_name.c
./ext/zip/lib/zip_source_close.c
./ext/zip/lib/zip_error_to_str.c
./ext/zip/lib/zip_memdup.c
./ext/zip/lib/zip_source_file.c
./ext/zip/lib/zip_unchange_archive.c
./ext/zip/lib/zip_open.c
./ext/zip/lib/zip_filerange_crc.c
./ext/zip/lib/zip_unchange.c
./ext/zip/lib/zip_get_file_comment.c
./ext/zip/lib/zip_set_default_password.c
./ext/zip/lib/zip_err_str.c
./ext/zip/lib/zip_source_pop.c
./ext/zip/lib/zip_source_open.c
./ext/zip/lib/zip_rename.c
./ext/zip/lib/zip_get_archive_comment.c
./ext/zip/lib/zip_file_error_clear.c
./ext/zip/lib/zip_set_archive_comment.c
./ext/zip/lib/zip_error.c
./ext/zip/lib/zip_add_dir.c
./ext/iconv/iconv.c
./ext/gmp/gmp.c
./ext/mbstring/mbstring.c
./ext/mbstring/mb_gpc.c
#./ext/mbstring/ucgendat/ucgendat.c
./ext/mbstring/php_unicode.c
./ext/mbstring/php_mbregex.c
./ext/sockets/sockets.c
./ext/tokenizer/tokenizer.c
./ext/tokenizer/tokenizer_data.c
./ext/simplexml/sxe.c
./ext/simplexml/simplexml.c
./ext/tidy/tidy.c
./ext/readline/readline.c
./ext/sqlite/sess_sqlite.c
./ext/sqlite/libsqlite/src/printf.c
./ext/sqlite/libsqlite/src/expr.c
./ext/sqlite/libsqlite/src/update.c
./ext/sqlite/libsqlite/src/encode.c
./ext/sqlite/libsqlite/src/table.c
./ext/sqlite/libsqlite/src/func.c
./ext/sqlite/libsqlite/src/opcodes.c
./ext/sqlite/libsqlite/src/vdbeaux.c
./ext/sqlite/libsqlite/src/pager.c
./ext/sqlite/libsqlite/src/date.c
./ext/sqlite/libsqlite/src/btree.c
./ext/sqlite/libsqlite/src/select.c
./ext/sqlite/libsqlite/src/btree_rb.c
./ext/sqlite/libsqlite/src/where.c
./ext/sqlite/libsqlite/src/vacuum.c
./ext/sqlite/libsqlite/src/trigger.c
./ext/sqlite/libsqlite/src/copy.c
./ext/sqlite/libsqlite/src/random.c
./ext/sqlite/libsqlite/src/vdbe.c
./ext/sqlite/libsqlite/src/auth.c
./ext/sqlite/libsqlite/src/attach.c
./ext/sqlite/libsqlite/src/parse.c
./ext/sqlite/libsqlite/src/tokenize.c
./ext/sqlite/libsqlite/src/pragma.c
./ext/sqlite/libsqlite/src/os.c
./ext/sqlite/libsqlite/src/build.c
./ext/sqlite/libsqlite/src/insert.c
./ext/sqlite/libsqlite/src/util.c
./ext/sqlite/libsqlite/src/hash.c
./ext/sqlite/libsqlite/src/delete.c
./ext/sqlite/libsqlite/src/main.c
./ext/pdo/pdo_sqlstate.c
./ext/pdo/pdo_dbh.c
./ext/pdo/pdo_sql_parser.c
./ext/pdo/pdo.c
./ext/pdo/pdo_stmt.c
./ext/sqlite/pdo_sqlite2.c
./ext/sqlite/sqlite.c
./ext/pcntl/php_signal.c
./ext/pcntl/pcntl.c
./ext/ctype/ctype.c
./ext/calendar/jewish.c
./ext/calendar/julian.c
./ext/calendar/dow.c
./ext/calendar/cal_unix.c
./ext/calendar/gregor.c
./ext/calendar/calendar.c
./ext/calendar/easter.c
./ext/calendar/french.c
./ext/recode/recode.c
./ext/libxml/libxml.c
./ext/shmop/shmop.c
./ext/pspell/pspell.c
./ext/filter/sanitizing_filters.c
./ext/filter/filter.c
./ext/filter/callback_filter.c
./ext/filter/logical_filters.c
./ext/wddx/wddx.c
./ext/date/php_date.c
./ext/date/lib/dow.c
./ext/date/lib/interval.c
./ext/date/lib/unixtime2tm.c
./ext/date/lib/parse_date.c
./ext/date/lib/astro.c
./ext/date/lib/parse_tz.c
./ext/date/lib/timelib.c
./ext/date/lib/parse_iso_intervals.c
./ext/date/lib/tm2unixtime.c
./ext/xmlreader/php_xmlreader.c
./ext/phar/phar_object.c
./ext/phar/phar_path_check.c
./ext/phar/func_interceptors.c
./ext/phar/stream.c
./ext/phar/zip.c
./ext/phar/dirstream.c
./ext/phar/phar.c
./ext/phar/tar.c
./ext/phar/util.c
./ext/sqlite3/sqlite3.c
./ext/sqlite3/libsqlite/sqlite3.c
./ext/reflection/php_reflection.c
./ext/exif/exif.c
./ext/posix/posix.c
./ext/sybase_ct/php_sybase_ct.c
./ext/fileinfo/fileinfo.c
#./ext/fileinfo/data_file.c
./ext/fileinfo/libmagic/apptype.c
./ext/fileinfo/libmagic/fsmagic.c
./ext/fileinfo/libmagic/apprentice.c
./ext/fileinfo/libmagic/cdf.c
./ext/fileinfo/libmagic/cdf_time.c
./ext/fileinfo/libmagic/is_tar.c
./ext/fileinfo/libmagic/compress.c
./ext/fileinfo/libmagic/readelf.c
./ext/fileinfo/libmagic/ascmagic.c
./ext/fileinfo/libmagic/print.c
./ext/fileinfo/libmagic/softmagic.c
./ext/fileinfo/libmagic/funcs.c
./ext/fileinfo/libmagic/encoding.c
./ext/fileinfo/libmagic/readcdf.c
./ext/fileinfo/libmagic/magic.c
#sapi
./sapi/cgi/cgi_main.c
./sapi/cgi/fastcgi.c
#./sapi/isapi/php5isapi.c
#./sapi/isapi/stresstest/getopt.c
#./sapi/thttpd/stub.c
#./sapi/thttpd/thttpd.c
#./sapi/nsapi/nsapi.c
#more see list.txt
)
