SET(OS_NET_SRC
./getsockopt.c
./bind.c
./netdev_unregister.c
./send.c
./netdev_txnotify.c
./netdev_findbyname.c
./netdev_register.c
./net_vfcntl.c
./net_checksd.c
./net_dsec2timeval.c
./accept.c
./net_arptimer.c
./netdev_count.c
./listen.c
./net_sockets.c
./net_dup.c
./setsockopt.c
./recvfrom.c
./netdev_findbyaddr.c
./netdev_foreach.c
./sendto.c
./net_monitor.c
./connect.c
./getsockname.c
./net_timeval2dsec.c
./netdev_sem.c
./net_poll.c
./net_close.c
./net_dup2.c
./netdev_ioctl.c
./recv.c
./socket.c
./net_clone.c
./uip/uip_chksum.c
./uip/uip_tcpreadahead.c
./uip/uip_icmpping.c
./uip/uip_udpcallback.c
./uip/uip_igmpmsg.c
./uip/uip_tcpcallback.c
./uip/uip_tcpappsend.c
./uip/uip_arptab.c
./uip/uip_igmppoll.c
./uip/uip_input.c
./uip/uip_igmpinput.c
./uip/uip_udpsend.c
./uip/uip_icmppoll.c
./uip/uip_tcpseqno.c
./uip/uip_igmpinit.c
./uip/uip_tcptimer.c
./uip/uip_udppoll.c
./uip/uip_send.c
./uip/uip_listen.c
./uip/uip_tcpsend.c
./uip/uip_tcpbacklog.c
./uip/uip_igmpgroup.c
./uip/uip_icmpinput.c
./uip/uip_initialize.c
./uip/uip_tcpinput.c
./uip/uip_igmpleave.c
./uip/uip_igmpjoin.c
./uip/uip_igmptimer.c
./uip/uip_neighbor.c
./uip/uip_tcppoll.c
./uip/uip_tcpconn.c
./uip/uip_udpconn.c
./uip/uip_udpinput.c
./uip/uip_poll.c
./uip/uip_lock.c
./uip/uip_icmpsend.c
./uip/uip_callback.c
./uip/uip_mcastmac.c
./uip/uip_arp.c
./uip/uip_setipid.c
./uip/uip_igmpsend.c
./net_timeo.c
)
